/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenDto } from '../../models/token-dto';
import { UsuarioCreateDto } from '../../models/usuario-create-dto';

export interface Registrar$Params {
  body: UsuarioCreateDto;
}

export function registrar(
  http: HttpClient,
  rootUrl: string,
  params: Registrar$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<TokenDto>> {
  const rb = new RequestBuilder(rootUrl, registrar.PATH, 'post');
  if (params) {
    const formData = new FormData();
    formData.append('nome', params.body.nome ?? '');
    formData.append('username', params.body.username ?? '');
    formData.append('email', params.body.email ?? '');
    formData.append('senha', params.body.senha ?? '');
    formData.append('confirmacaoSenha', params.body.confirmacaoSenha ?? '');

    if (params.body.bio) {
      formData.append('bio', params.body.bio);
    }

    if (params.body.fotoPerfil) {
      formData.append('fotoPerfil', params.body.fotoPerfil);
    }

    rb.body(formData);
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<TokenDto>;
      })
    );
}

registrar.PATH = '/auth/register';
