/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface SessaoAtiva {
  dataCriacao?: string;
  expiracao?: string;
  jti?: string;
}

export function listarSessoes(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<Array<SessaoAtiva>>> {
  const rb = new RequestBuilder(rootUrl, listarSessoes.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SessaoAtiva>>;
    })
  );
}

listarSessoes.PATH = '/auth/sessoes';

export interface RevogarSessao$Params {

/**
 * JTI da sessão
 */
  jti: string;
}

export function revogarSessao(http: HttpClient, rootUrl: string, params: RevogarSessao$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, revogarSessao.PATH, 'delete');
  if (params) {
    rb.path('jti', params.jti, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

revogarSessao.PATH = '/auth/sessoes/{jti}';

export function revogarTodasSessoes(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, revogarTodasSessoes.PATH, 'delete');

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

revogarTodasSessoes.PATH = '/auth/sessoes';
