/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AnalyticsDto } from './models/analytics-dto';
export type { BuscarResponseDto } from './models/buscar-response-dto';
export type { ComentarioCreateDto } from './models/comentario-create-dto';
export type { ConversaResponseDto } from './models/conversa-response-dto';
export type { ContagemSeguidoresDto } from './models/contagem-seguidores-dto';
export type { ContagemStoriesDto } from './models/contagem-stories-dto';
export type { ComentarioResponseDto } from './models/comentario-response-dto';
export type { ComentarioUpdateDto } from './models/comentario-update-dto';
export type { DestaqueCreateDto } from './models/destaque-create-dto';
export type { DestaqueResponseDto } from './models/destaque-response-dto';
export type { DestaqueSummaryDto } from './models/destaque-summary-dto';
export type { DestaqueUpdateDto } from './models/destaque-update-dto';
export type { HashtagResponseDto } from './models/hashtag-response-dto';
export type { HashtagSummaryDto } from './models/hashtag-summary-dto';
export type { LoginDto } from './models/login-dto';
export type { MensagemResponseDto } from './models/mensagem-response-dto';
export type { NotificacaoResponseDto } from './models/notificacao-response-dto';
export type { Page } from './models/page';
export type { StatusNotaDto } from './models/status-nota-dto';
export type { Pageable } from './models/pageable';
export type { PollOpcaoResponseDto, PollResponseDto } from './models/poll-response-dto';
export type { PageableObject } from './models/pageable-object';
export type { PageHashtagSummaryDto } from './models/page-hashtag-summary-dto';
export type { RefreshTokenDto } from './models/refresh-token-dto';
export type { PostCreateDto } from './models/post-create-dto';
export type { PostResponseDto } from './models/post-response-dto';
export type { PostUpdateDto } from './models/post-update-dto';
export type { SeguidorResponseDto } from './models/seguidor-response-dto';
export type { SortObject } from './models/sort-object';
export type { StorieCreateDto } from './models/storie-create-dto';
export type { StorieResponseDto } from './models/storie-response-dto';
export type { TokenDto } from './models/token-dto';
export type { UsuarioCreateDto } from './models/usuario-create-dto';
export type { UsuarioResponseDto } from './models/usuario-response-dto';
export type { UsuarioSummaryDto } from './models/usuario-summary-dto';
export type { UsuarioUpdateDto } from './models/usuario-update-dto';
export type { VerificarSeguimentoDto } from './models/verificar-seguimento-dto';
