/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UsuariosService } from './services/usuarios.service';
export { PostsService } from './services/posts.service';
export { AutenticacaoService } from './services/autenticacao.service';
