/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { BuscarResponseDto } from '../models/buscar-response-dto';
import { Pageable } from '../models/pageable';

export interface Buscar$Params {

/**
 * Termo de busca
 */
  q: string;

/**
 * Parâmetros de paginação (page=0, size=10)
 */
  pageable: Pageable;
}

export function buscar(http: HttpClient, rootUrl: string, params: Buscar$Params, context?: HttpContext): Observable<StrictHttpResponse<BuscarResponseDto>> {
  const rb = new RequestBuilder(rootUrl, buscar.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BuscarResponseDto>;
    })
  );
}

buscar.PATH = '/buscar';
