/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { ConversaResponseDto } from '../models/conversa-response-dto';
import { MensagemResponseDto } from '../models/mensagem-response-dto';
import { Page } from '../models/page';
import { Pageable } from '../models/pageable';

export interface IniciarConversa$Params {

/**
 * ID do outro usuário
 */
  usuarioId: number;
}

export function iniciarConversa(http: HttpClient, rootUrl: string, params: IniciarConversa$Params, context?: HttpContext): Observable<StrictHttpResponse<ConversaResponseDto>> {
  const rb = new RequestBuilder(rootUrl, iniciarConversa.PATH, 'post');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConversaResponseDto>;
    })
  );
}

iniciarConversa.PATH = '/conversas/iniciar/{usuarioId}';

export interface ListarConversas$Params {

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarConversas(http: HttpClient, rootUrl: string, params: ListarConversas$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarConversas.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarConversas.PATH = '/conversas';

export interface ListarMensagens$Params {

/**
 * ID da conversa
 */
  id: number;

/**
 * Parâmetros de paginação (page=0, size=50)
 */
  pageable: Pageable;
}

export function listarMensagens(http: HttpClient, rootUrl: string, params: ListarMensagens$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarMensagens.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarMensagens.PATH = '/conversas/{id}/mensagens';

export interface EnviarMensagem$Params {

/**
 * ID da conversa
 */
  id: number;
  body: {
    texto: string;
  };
}

export function enviarMensagem(http: HttpClient, rootUrl: string, params: EnviarMensagem$Params, context?: HttpContext): Observable<StrictHttpResponse<MensagemResponseDto>> {
  const rb = new RequestBuilder(rootUrl, enviarMensagem.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MensagemResponseDto>;
    })
  );
}

enviarMensagem.PATH = '/conversas/{id}/mensagens';

export function contarMensagensNaoLidas(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
  const rb = new RequestBuilder(rootUrl, contarMensagensNaoLidas.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: number;
      }>;
    })
  );
}

contarMensagensNaoLidas.PATH = '/conversas/nao-lidas/contagem';
