/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { PollResponseDto } from '../models/poll-response-dto';

export interface CriarEnquete$Params {
  body: {
    pergunta: string;
    postId?: number;
    storieId?: number;
    opcoes: Array<string>;
    encerraEm?: string;
  };
}

export function criarEnquete(http: HttpClient, rootUrl: string, params: CriarEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResponseDto>> {
  const rb = new RequestBuilder(rootUrl, criarEnquete.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PollResponseDto>;
    })
  );
}

criarEnquete.PATH = '/enquetes';

export interface VotarEnquete$Params {

/**
 * ID da enquete
 */
  id: number;
  body: {
    opcaoId: number;
  };
}

export function votarEnquete(http: HttpClient, rootUrl: string, params: VotarEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResponseDto>> {
  const rb = new RequestBuilder(rootUrl, votarEnquete.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PollResponseDto>;
    })
  );
}

votarEnquete.PATH = '/enquetes/{id}/votar';

export interface ExcluirEnquete$Params {

/**
 * ID da enquete
 */
  id: number;
}

export function excluirEnquete(http: HttpClient, rootUrl: string, params: ExcluirEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, excluirEnquete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

excluirEnquete.PATH = '/enquetes/{id}';
