/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { Page } from '../models/page';
import { Pageable } from '../models/pageable';

export type AlvoDenuncia = 'POST' | 'COMENTARIO' | 'USUARIO';

export interface Denunciar$Params {
  body: {
    tipoAlvo: AlvoDenuncia;
    alvoId: number;
    motivo: string;
    descricao?: string;
  };
}

export function denunciar(http: HttpClient, rootUrl: string, params: Denunciar$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, denunciar.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

denunciar.PATH = '/moderacao/denuncias';

export interface Bloquear$Params {

/**
 * ID do usuário a bloquear
 */
  usuarioId: number;
}

export function bloquear(http: HttpClient, rootUrl: string, params: Bloquear$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, bloquear.PATH, 'post');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

bloquear.PATH = '/moderacao/bloqueios/{usuarioId}';

export interface Desbloquear$Params {

/**
 * ID do usuário
 */
  usuarioId: number;
}

export function desbloquear(http: HttpClient, rootUrl: string, params: Desbloquear$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, desbloquear.PATH, 'delete');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

desbloquear.PATH = '/moderacao/bloqueios/{usuarioId}';

export interface VerificarBloqueio$Params {

/**
 * ID do usuário
 */
  usuarioId: number;
}

export interface BloqueioStatus {
  bloqueado?: boolean;
}

export function verificarBloqueio(http: HttpClient, rootUrl: string, params: VerificarBloqueio$Params, context?: HttpContext): Observable<StrictHttpResponse<BloqueioStatus>> {
  const rb = new RequestBuilder(rootUrl, verificarBloqueio.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BloqueioStatus>;
    })
  );
}

verificarBloqueio.PATH = '/moderacao/bloqueios/verificar/{usuarioId}';

export interface ListarBloqueios$Params {

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarBloqueios(http: HttpClient, rootUrl: string, params: ListarBloqueios$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarBloqueios.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarBloqueios.PATH = '/moderacao/bloqueios';

export type StatusDenuncia = 'ABERTA' | 'EM_ANALISE' | 'RESOLVIDA' | 'REJEITADA';

export interface DenunciaDto {
  alvoId?: number;
  dataCriacao?: string;
  descricao?: string;
  id?: number;
  motivo?: string;
  status?: StatusDenuncia;
  tipoAlvo?: 'POST' | 'COMENTARIO' | 'USUARIO';
}

export interface ListarFila$Params {

/**
 * Filtra por status (vazio = todas)
 */
  status?: StatusDenuncia;

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarFila(http: HttpClient, rootUrl: string, params: ListarFila$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarFila.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarFila.PATH = '/moderacao/denuncias';

export interface ResolverDenuncia$Params {

/**
 * ID da denúncia
 */
  id: number;

/**
 * Novo status
 */
  status: 'EM_ANALISE' | 'RESOLVIDA' | 'REJEITADA';
}

export function resolverDenuncia(http: HttpClient, rootUrl: string, params: ResolverDenuncia$Params, context?: HttpContext): Observable<StrictHttpResponse<DenunciaDto>> {
  const rb = new RequestBuilder(rootUrl, resolverDenuncia.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DenunciaDto>;
    })
  );
}

resolverDenuncia.PATH = '/moderacao/denuncias/{id}';
