/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { NotificacaoResponseDto } from '../models/notificacao-response-dto';
import { Page } from '../models/page';
import { Pageable } from '../models/pageable';

export interface ListarNotificacoes$Params {

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarNotificacoes(http: HttpClient, rootUrl: string, params: ListarNotificacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarNotificacoes.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarNotificacoes.PATH = '/notificacoes';

export function contarNaoLidas(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
  const rb = new RequestBuilder(rootUrl, contarNaoLidas.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: number;
      }>;
    })
  );
}

contarNaoLidas.PATH = '/notificacoes/contagem';

export interface MarcarComoVisualizada$Params {

/**
 * ID da notificação
 */
  id: number;
}

export function marcarComoVisualizada(http: HttpClient, rootUrl: string, params: MarcarComoVisualizada$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, marcarComoVisualizada.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

marcarComoVisualizada.PATH = '/notificacoes/{id}/visualizar';

export function marcarTodasComoVisualizadas(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, marcarTodasComoVisualizadas.PATH, 'patch');

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

marcarTodasComoVisualizadas.PATH = '/notificacoes/visualizar-todas';

export interface DeletarNotificacao$Params {

/**
 * ID da notificação
 */
  id: number;
}

export function deletarNotificacao(http: HttpClient, rootUrl: string, params: DeletarNotificacao$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deletarNotificacao.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deletarNotificacao.PATH = '/notificacoes/{id}';

export type { NotificacaoResponseDto };
