/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../strict-http-response';
import { RequestBuilder } from '../request-builder';

import { StatusNotaDto } from '../models/status-nota-dto';
import { StatusUsuarioResponseDto } from '../models/status-usuario-response-dto';

export function listarNotas(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<Array<StatusNotaDto>>> {
  const rb = new RequestBuilder(rootUrl, listarNotas.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StatusNotaDto>>;
    })
  );
}

listarNotas.PATH = '/status/notas';

export interface DefinirNota$Params {
  body: {
    nota?: string;
  };
}

export function definirNota(http: HttpClient, rootUrl: string, params: DefinirNota$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusNotaDto>> {
  const rb = new RequestBuilder(rootUrl, definirNota.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatusNotaDto>;
    })
  );
}

definirNota.PATH = '/status/nota';

export interface StatusPorUsuario$Params {

/**
 * ID do usuário
 */
  usuarioId: number;
}

export function statusPorUsuario(http: HttpClient, rootUrl: string, params: StatusPorUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusUsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, statusPorUsuario.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatusUsuarioResponseDto>;
    })
  );
}

statusPorUsuario.PATH = '/status/{usuarioId}';
