/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponseDto } from '../../models/usuario-response-dto';

export interface AtualizarPrivado$Params {

/**
 * ID do usuário
 */
  id: number;

/**
 * Conta privada?
 */
  privado: boolean;
}

export function atualizarPrivado(http: HttpClient, rootUrl: string, params: AtualizarPrivado$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarPrivado.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('privado', params.privado, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

atualizarPrivado.PATH = '/usuarios/{id}/privado';
