/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponseDto } from '../../models/usuario-response-dto';
import { UsuarioUpdateDto } from '../../models/usuario-update-dto';

export interface AtualizarUsuario$Params {

/**
 * ID do usuário
 */
  id: number;
      body: UsuarioUpdateDto
}

export function atualizarUsuario(http: HttpClient, rootUrl: string, params: AtualizarUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarUsuario.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

atualizarUsuario.PATH = '/usuarios/{id}';
