/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponseDto } from '../../models/usuario-response-dto';
import { UsuarioSummaryDto } from '../../models';

export interface BuscarUsuarioPorId$Params {

/**
 * ID do usuário
 */
  id: number;
}

export function buscarUsuarioPorId(http: HttpClient, rootUrl: string, params: BuscarUsuarioPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, buscarUsuarioPorId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioSummaryDto>;
    })
  );
}

buscarUsuarioPorId.PATH = '/usuarios/{id}';
