/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioResponseDto } from '../../models/usuario-response-dto';

export interface BuscarUsuarioPorUsername$Params {

/**
 * Username do usuário
 */
  username: string;
}

export function buscarUsuarioPorUsername(http: HttpClient, rootUrl: string, params: BuscarUsuarioPorUsername$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, buscarUsuarioPorUsername.PATH, 'get');
  if (params) {
    rb.path('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

buscarUsuarioPorUsername.PATH = '/usuarios/username/{username}';
