/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AnalyticsDto } from '../../models/analytics-dto';
import { UsuarioResponseDto } from '../../models/usuario-response-dto';

export function analytics(http: HttpClient, rootUrl: string, context?: HttpContext): Observable<StrictHttpResponse<AnalyticsDto>> {
  const rb = new RequestBuilder(rootUrl, analytics.PATH, 'get');

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AnalyticsDto>;
    })
  );
}

analytics.PATH = '/usuarios/eu/analytics';

export interface AtualizarChavePix$Params {
  body: {
    chavePix?: string;
  };
}

export function atualizarChavePix(http: HttpClient, rootUrl: string, params: AtualizarChavePix$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarChavePix.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

atualizarChavePix.PATH = '/usuarios/eu/pix';

export interface AtualizarTipoConta$Params {

/**
 * Tipo de conta
 */
  tipoConta: 'PESSOAL' | 'CRIADOR' | 'NEGOCIOS';
}

export function atualizarTipoConta(http: HttpClient, rootUrl: string, params: AtualizarTipoConta$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarTipoConta.PATH, 'patch');
  if (params) {
    rb.query('tipoConta', params.tipoConta, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UsuarioResponseDto>;
    })
  );
}

atualizarTipoConta.PATH = '/usuarios/eu/tipo-conta';
