/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface  SalvarFotoDePerfil$Params {
  id: number;
  body?: {
    /**
     * Imagem da foto de perfil
     */
    file: Blob;
  };
}

export function salvarFotoDePerfil(
  http: HttpClient,
  rootUrl: string,
  params: SalvarFotoDePerfil$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, salvarFotoDePerfil.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }
  rb.header('Authorization', 'Bearer ' + localStorage.getItem('token')); 
  return http
    .request(rb.build({ responseType: 'json', accept: '*/*', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return (r as HttpResponse<any>).clone({
          body: parseFloat(String((r as HttpResponse<any>).body)),
        }) as StrictHttpResponse<number>;
      })
    );
}

salvarFotoDePerfil.PATH = '/usuarios/foto-de-perfil/{id}';
