/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnalyticsDto {
  alcance7d?: number;
  posts?: number;
  seguidores?: number;
  views30d?: number;
  views7d?: number;
}
