/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArquivoDto {
  contentType?: string;
  id?: number;
  nomeOriginal?: string;
  tamanho?: number;
  tipo?: string;
  url?: string;
}
