/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HashtagSummaryDto } from './hashtag-summary-dto';
import { Page } from './page';
import { UsuarioSummaryDto } from './usuario-summary-dto';

export interface BuscarResponseDto {
  hashtags?: Page & { content?: Array<HashtagSummaryDto> };
  posts?: Page & { content?: Array<any> };
  usuarios?: Page & { content?: Array<UsuarioSummaryDto> };
}
