/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioSummaryDto } from '../models/usuario-summary-dto';
export interface ComentarioResponseDto {
  autor?: UsuarioSummaryDto;
  comentarioPaiId?: number;
  curtidoPeloUsuario?: boolean;
  dataCriacao?: string;
  id?: number;
  numeroCurtidas?: number;
  numeroRespostas?: number;
  postId?: number;
  texto?: string;
}
