/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados do comentário a ser criado
 */
export interface ComentarioCreateDto {
  comentarioPaiId?: number;
  postId?: number;
  texto?: string;
}
