/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para atualização do comentário
 */
export interface ComentarioUpdateDto {
  texto?: string;
}
