/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para atualização do comentário
 */
export interface ComentarioUpdateDto {

  /**
   * Novo texto do comentário
   */
  texto?: string;
}
