/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConversaResponseDto {
  dataAtualizacao?: string;
  id?: number;
  naoLidas?: number;
  outroParticipanteFotoPerfil?: string;
  outroParticipanteId?: number;
  outroParticipanteNome?: string;
  outroParticipanteUsername?: string;
  ultimaMensagem?: string;
}
