/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DestaqueUpdateDto {

  /**
   * Descrição do destaque
   */
  descricao?: string;

  /**
   * Nome do destaque
   */
  nome?: string;

  /**
   * Lista de IDs das stories para adicionar ao destaque
   */
  storiesParaAdicionar?: Array<number>;

  /**
   * Lista de IDs das stories para remover do destaque
   */
  storiesParaRemover?: Array<number>;
}
