/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DestaqueSummaryDto {

  /**
   * Data de criação do destaque
   */
  dataCriacao?: string;

  /**
   * URL da foto de capa do destaque
   */
  destaqueFotoDeCapaUrl?: string;

  /**
   * ID do destaque
   */
  id?: number;

  /**
   * Nome do destaque
   */
  nome?: string;

  /**
   * Quantidade de stories associadas ao destaque
   */
  quantidadeStories?: number;
}
