/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StorieResponseDto } from '../models/storie-response-dto';
export interface DestaqueResponseDto {

  /**
   * Data de criação do destaque
   */
  dataCriacao?: string;

  /**
   * URL da foto de capa do destaque
   */
  destaqueFotoDeCapaUrl?: string;

  /**
   * ID do destaque
   */
  id?: number;

  /**
   * Nome do destaque
   */
  nome?: string;

  /**
   * Quantidade de stories associadas ao destaque
   */
  quantidadeStories?: number;

  /**
   * Lista de stories associadas ao destaque
   */
  stories?: Array<StorieResponseDto>;

  /**
   * Nome de usuário do criador do destaque
   */
  usernameUsuario?: string;

  /**
   * ID do usuário que criou o destaque
   */
  usuarioId?: number;
}
