/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HashtagSummaryDto {

  /**
   * Nome da hashtag
   */
  nome?: string;

  /**
   * Quantidade de posts associados à hashtag
   */
  quantidadePosts?: number;
}
