/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Credenciais de login do usuário
 */
export interface LoginDto {

  /**
   * E-mail do usuário
   */
  email?: string;

  /**
   * Senha do usuário
   */
  senha?: string;
}
