/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Credenciais de login do usuário
 */
export interface LoginDto {
  email?: string;
  senha?: string;
}
