/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MensagemResponseDto {
  conversaId?: number;
  dataCriacao?: string;
  id?: number;
  lida?: boolean;
  minha?: boolean;
  remetenteId?: number;
  texto?: string;
}
