/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificacaoResponseDto {
  conteudo?: string;
  dataCriacao?: string;
  destinatarioId?: number;
  fotoPerfilRemetente?: string;
  id?: number;
  lida?: boolean;
  nomeRemetente?: string;
  remetenteId?: number;
  tipo?: 'SEGUIDOR' | 'COMENTARIO' | 'CURTIDA' | 'MENSAGEM' | 'NOVO_SEGUIDOR' | 'SOLICITACAO_SEGUIMENTO';
  usernameRemetente?: string;
}
