/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PollOpcaoResponseDto {
  id?: number;
  percentual?: number;
  texto?: string;
  votos?: number;
}

export interface PollResponseDto {
  encerraEm?: string;
  encerrada?: boolean;
  id?: number;
  minhaOpcaoId?: number;
  opcoes?: Array<PollOpcaoResponseDto>;
  pergunta?: string;
  totalVotos?: number;
}
