/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioSummaryDto } from '../models/usuario-summary-dto';

/**
 * DTO para resposta de um post
 */
export interface PostResponseDto {

  /**
   * Indica se o post está arquivado
   */
  arquivado?: boolean;

  /**
   * Informações do autor do post
   */
  autor?: UsuarioSummaryDto;

  /**
   * Indica se o post foi curtido pelo usuário
   */
  curtidoPeloUsuario?: boolean;

  /**
   * Data de criação do post
   */
  dataCriacao?: string;

  /**
   * Lista de hashtags associadas ao post
   */
  hashtags?: Array<string>;

  /**
   * ID do post
   */
  id?: number;

  /**
   * Legenda do post
   */
  legenda?: string;

  /**
   * Localização associada ao post
   */
  localizacao?: string;

  /**
   * Número de comentários no post
   */
  numeroComentarios?: number;

  /**
   * Número de curtidas no post
   */
  numeroCurtidas?: number;

  /**
   * Indica se o post foi salvo pelo usuário
   */
  salvoPeloUsuario?: boolean;

  /**
   * Lista de usuários marcados no post
   */
  usuariosMarcados?: Array<UsuarioSummaryDto>;

  /**
   * Visibilidade do post
   */
  visibilidade?: 'PUBLICO' | 'PRIVADO' | 'SOMENTE_SEGUIDORES';
}
