/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para atualização do post
 */
export interface PostUpdateDto {
  hashtags?: Array<string>;
  legenda?: string;
  localizacao?: string;
  usuariosMarcados?: Array<number>;
  visibilidade?: 'PUBLICO' | 'PRIVADO' | 'SOMENTE_SEGUIDORES';
}
