/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArquivoDto } from '../models/arquivo-dto';
import { UsuarioSummaryDto } from '../models/usuario-summary-dto';
export interface PostResponseDto {
  arquivado?: boolean;
  arquivos?: Array<ArquivoDto>;
  autor?: UsuarioSummaryDto;
  curtidoPeloUsuario?: boolean;
  dataCriacao?: string;
  hashtags?: Array<string>;
  id?: number;
  legenda?: string;
  localizacao?: string;
  numeroComentarios?: number;
  numeroCurtidas?: number;
  salvoPeloUsuario?: boolean;
  usuariosMarcados?: Array<UsuarioSummaryDto>;
  visibilidade?: 'PUBLICO' | 'PRIVADO' | 'SOMENTE_SEGUIDORES';
}
