/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeguidorResponseDto {

  /**
   * Data de criação da relação de seguidor
   */
  dataCriacao?: string;

  /**
   * ID da relação de seguidor
   */
  id?: number;

  /**
   * Indica se as notificações estão ativadas
   */
  notificacoesAtivadas?: boolean;

  /**
   * URL da foto de perfil do usuário seguido
   */
  seguidoFotoPerfil?: string;

  /**
   * ID do usuário seguido
   */
  seguidoId?: number;

  /**
   * Nome do usuário seguido
   */
  seguidoNome?: string;

  /**
   * Username do usuário seguido
   */
  seguidoUsername?: string;

  /**
   * Indica se o usuário seguido é verificado
   */
  seguidoVerificado?: boolean;

  /**
   * URL da foto de perfil do seguidor
   */
  seguidorFotoPerfil?: string;

  /**
   * ID do seguidor
   */
  seguidorId?: number;

  /**
   * Nome do seguidor
   */
  seguidorNome?: string;

  /**
   * Username do seguidor
   */
  seguidorUsername?: string;

  /**
   * Indica se o seguidor é verificado
   */
  seguidorVerificado?: boolean;
}
