/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatusNotaDto {
  fotoPerfil?: string;
  nome?: string;
  nota?: string;
  ultimoAcesso?: string;
  username?: string;
  usuarioId?: number;
}
