/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatusUsuarioResponseDto {
  id?: number;
  online?: boolean;
  statusPersonalizado?: string;
  ultimoAcesso?: string;
  usuarioId?: number;
}
