/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO para criação de uma storie
 */
export interface StorieCreateDto {

  /**
   * Indica se a storie deve ser destacada
   */
  destacar?: boolean;

  /**
   * Imagem do Storie
   */
  imagem?: Blob[];
}
