/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UsuarioSummaryDto } from '../models/usuario-summary-dto';

/**
 * DTO para resposta de uma storie
 */
export interface StorieResponseDto {

  /**
   * Informações do autor da storie
   */
  autor?: UsuarioSummaryDto;
  autorId?: number;
  autorUsername?: string;

  /**
   * Data de criação da storie
   */
  dataCriacao?: string;

  /**
   * Data de expiração da storie
   */
  dataExpiracao?: string;

  /**
   * Indica se a storie está destacada
   */
  destacado?: boolean;

  /**
   * ID da storie
   */
  id?: number;

  /**
   * Número de visualizações da storie
   */
  numeroVisualizacoes?: number;
  storieImagemUrl?: string;

  /**
   * Indica se a storie foi visualizada pelo usuário
   */
  visualizadoPeloUsuario?: boolean;
}
