/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TokenDto {

  /**
   * Token de atualização do usuário
   */
  refreshToken?: string;

  /**
   * Token de acesso do usuário
   */
  token?: string;
}
