/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioResponseDto {

  /**
   * Biografia do usuário
   */
  bio?: string;

  /**
   * Data de cadastro do usuário
   */
  dataCadastro?: string;

  /**
   * E-mail do usuário
   */
  email?: string;

  /**
   * Foto de perfil do usuário em formato binário
   */
  fotoPerfil?: Blob;

  /**
   * URL da foto de perfil do usuário
   */
  fotoPerfilUrl?: string;

  /**
   * ID do usuário
   */
  id?: number;

  /**
   * Nome completo do usuário
   */
  nome?: string;

  /**
   * Número de posts do usuário
   */
  numeroPosts?: number;

  /**
   * Número de seguidores do usuário
   */
  numeroSeguidores?: number;

  /**
   * Número de usuários que o usuário está seguindo
   */
  numeroSeguindo?: number;

  /**
   * Indica se o usuário atual está seguindo este usuário
   */
  seguindoUsuario?: boolean;

  /**
   * Indica se a conta é privada
   */
  privado?: boolean;

  /**
   * Selo de verificação
   */
  verificado?: boolean;

  /**
   * E-mail verificado
   */
  emailVerificado?: boolean;

  /**
   * Chave Pix para gorjetas
   */
  chavePix?: string;

  /**
   * Tipo da conta
   */
  tipoConta?: 'PESSOAL' | 'CRIADOR' | 'NEGOCIOS';

  /**
   * Nome de usuário único
   */
  username?: string;
}
