/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioSummaryDto {
  fotoPerfil?: string;

  /**
   * ID do usuário
   */
  id?: number;

  /**
   * Nome completo do usuário
   */
  nome?: string;

  /**
   * Número de posts do usuário
   */
  numeroPosts?: number;

  /**
   * Número de seguidores do usuário
   */
  numeroSeguidores?: number;

  /**
   * Número de usuários que o usuário está seguindo
   */
  numeroSeguindo?: number;

  /**
   * Indica se o usuário atual está seguindo este usuário
   */
  seguindoUsuario?: boolean;

  /**
   * Nome de usuário único
   */
  username?: string;
}
