/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UsuarioResponseDto {
  bio?: string;
  dataCadastro?: string;
  email?: string;
  fotoPerfilUrl?: string;
  id?: number;
  nome?: string;
  numeroPosts?: number;
  numeroSeguidores?: number;
  numeroSeguindo?: number;
  seguindoUsuario?: boolean;
  username?: string;
}
