/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArquivoDto } from '../models/arquivo-dto';
export interface UsuarioSummaryDto {
  fotoPerfil?: ArquivoDto;
  id?: number;
  nome?: string;
  seguindoUsuario?: boolean;
  username?: string;
}
