/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados do usuário a ser registrado
 */
export interface UsuarioCreateDto {
  bio?: string;
  confirmacaoSenha?: string;
  email?: string;
  nome?: string;
  senha?: string;
  username?: string;
}
