/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados para atualização do usuário
 */
export interface UsuarioUpdateDto {
  bio?: string;
  nome?: string;
}
