/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dados do usuário a ser registrado
 */
export interface UsuarioCreateDto {

  /**
   * Biografia do usuário
   */
  bio?: string;

  /**
   * Confirmação da senha
   */
  confirmacaoSenha?: string;

  /**
   * E-mail do usuário
   */
  email?: string;

  /**
   * Foto de perfil do usuário
   */
  fotoPerfil?: Blob;

  /**
   * Nome completo do usuário
   */
  nome?: string;

  /**
   * Senha do usuário
   */
  senha?: string;

  /**
   * Nome de usuário único
   */
  username?: string;
}
