/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostResponseDto } from '../../models/post-response-dto';
import { PostUpdateDto } from '../../models/post-update-dto';

export interface AtualizarPost$Params {

/**
 * ID do post
 */
  id: number;
      body: PostUpdateDto
}

export function atualizarPost(http: HttpClient, rootUrl: string, params: AtualizarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
  const rb = new RequestBuilder(rootUrl, atualizarPost.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PostResponseDto>;
    })
  );
}

atualizarPost.PATH = '/posts/{id}';
