/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostCreateDto } from '../../models/post-create-dto';
import { PostResponseDto } from '../../models/post-response-dto';

export interface CriarPost$Params {
  body?: PostCreateDto;
}

export function criarPost(
  http: HttpClient,
  rootUrl: string,
  params?: CriarPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<PostResponseDto>> {
  const rb = new RequestBuilder(rootUrl, criarPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }
  rb.header('Authorization', 'Bearer ' + localStorage.getItem('token')); 
  return http
    .request(rb.build({ responseType: 'json', accept: '*/*', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<PostResponseDto>;
      })
    );
}

criarPost.PATH = '/posts';
