/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostCreateDto } from '../../models/post-create-dto';
import { PostResponseDto } from '../../models/post-response-dto';

export interface CriarPost$Params {
      body?: {
'post': PostCreateDto;

/**
 * Arquivos a serem anexados ao post
 */
'arquivos'?: Array<Blob>;
}
}

export function criarPost(http: HttpClient, rootUrl: string, params?: CriarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
  const rb = new RequestBuilder(rootUrl, criarPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PostResponseDto>;
    })
  );
}

criarPost.PATH = '/posts';
