/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostResponseDto } from '../../models/post-response-dto';

export interface CurtirPost$Params {

/**
 * ID do post
 */
  id: number;
}

export function curtirPost(http: HttpClient, rootUrl: string, params: CurtirPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
  const rb = new RequestBuilder(rootUrl, curtirPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PostResponseDto>;
    })
  );
}

curtirPost.PATH = '/posts/{id}/curtir';
