/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Page } from '../../models/page';
import { Pageable } from '../../models/pageable';

export interface ListarPostsDoUsuario$Params {

/**
 * ID do usuário
 */
  usuarioId: number;

/**
 * Parâmetros de paginação (page=0, size=10, sort=dataCriacao,desc)
 */
  pageable: Pageable;
}

export function listarPostsDoUsuario(http: HttpClient, rootUrl: string, params: ListarPostsDoUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarPostsDoUsuario.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarPostsDoUsuario.PATH = '/posts/usuario/{usuarioId}';
