/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestaqueResponseDto } from '../../models/destaque-response-dto';

export interface AdicionarCapaDestaque$Params {

/**
 * ID do destaque
 */
  id: number;
      body?: {

/**
 * Arquivo de imagem da capa
 */
'arquivo': Blob;
}
}

export function adicionarCapaDestaque(http: HttpClient, rootUrl: string, params: AdicionarCapaDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
  const rb = new RequestBuilder(rootUrl, adicionarCapaDestaque.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DestaqueResponseDto>;
    })
  );
}

adicionarCapaDestaque.PATH = '/destaques/{id}/capa';
