/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestaqueResponseDto } from '../../models/destaque-response-dto';

export interface BuscarDestaquePorId$Params {

/**
 * ID do destaque
 */
  id: number;
}

export function buscarDestaquePorId(http: HttpClient, rootUrl: string, params: BuscarDestaquePorId$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
  const rb = new RequestBuilder(rootUrl, buscarDestaquePorId.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DestaqueResponseDto>;
    })
  );
}

buscarDestaquePorId.PATH = '/destaques/{id}';
