/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestaqueCreateDto } from '../../models/destaque-create-dto';
import { DestaqueResponseDto } from '../../models/destaque-response-dto';

export interface CriarDestaque$Params {
      body?: DestaqueCreateDto
}

export function criarDestaque(http: HttpClient, rootUrl: string, params?: CriarDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
  const rb = new RequestBuilder(rootUrl, criarDestaque.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DestaqueResponseDto>;
    })
  );
}

criarDestaque.PATH = '/destaques';
