/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DestaqueResponseDto } from '../../models/destaque-response-dto';

export interface ListarDestaquesPorUsername$Params {
  username: string;
}

export function listarDestaquesPorUsername(http: HttpClient, rootUrl: string, params: ListarDestaquesPorUsername$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DestaqueResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, listarDestaquesPorUsername.PATH, 'get');
  if (params) {
    rb.path('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DestaqueResponseDto>>;
    })
  );
}

listarDestaquesPorUsername.PATH = '/destaques/usuario/{username}';
