/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorieResponseDto } from '../../models/storie-response-dto';

export interface ListarStoriesPorDestaque$Params {

/**
 * ID do destaque
 */
  id: number;
}

export function listarStoriesPorDestaque(http: HttpClient, rootUrl: string, params: ListarStoriesPorDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorieResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, listarStoriesPorDestaque.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StorieResponseDto>>;
    })
  );
}

listarStoriesPorDestaque.PATH = '/destaques/{id}/stories';
