/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HashtagResponseDto } from '../../models/hashtag-response-dto';

export interface BuscarPorNome$Params {

/**
 * Nome da hashtag
 */
  nome: string;
}

export function buscarPorNome(http: HttpClient, rootUrl: string, params: BuscarPorNome$Params, context?: HttpContext): Observable<StrictHttpResponse<HashtagResponseDto>> {
  const rb = new RequestBuilder(rootUrl, buscarPorNome.PATH, 'get');
  if (params) {
    rb.path('nome', params.nome, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HashtagResponseDto>;
    })
  );
}

buscarPorNome.PATH = '/hashtags/{nome}';
