/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageHashtagSummaryDto } from '../../models/page-hashtag-summary-dto';

export interface BuscarHashtags$Params {

/**
 * Termo de busca
 */
  termo: string;
  pageable: Pageable;
}

export function buscarHashtags(http: HttpClient, rootUrl: string, params: BuscarHashtags$Params, context?: HttpContext): Observable<StrictHttpResponse<PageHashtagSummaryDto>> {
  const rb = new RequestBuilder(rootUrl, buscarHashtags.PATH, 'get');
  if (params) {
    rb.query('termo', params.termo, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageHashtagSummaryDto>;
    })
  );
}

buscarHashtags.PATH = '/hashtags/buscar';
