/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HashtagSummaryDto } from '../../models/hashtag-summary-dto';

export interface SugerirHashtags$Params {

/**
 * Termo de busca
 */
  termo: string;

/**
 * Limite de resultados
 */
  limite?: number;
}

export function sugerirHashtags(http: HttpClient, rootUrl: string, params: SugerirHashtags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HashtagSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, sugerirHashtags.PATH, 'get');
  if (params) {
    rb.query('termo', params.termo, {});
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HashtagSummaryDto>>;
    })
  );
}

sugerirHashtags.PATH = '/hashtags/sugestoes';
