/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorieResponseDto } from '../../models/storie-response-dto';

export interface AdicionarImagemStorie$Params {

/**
 * ID do storie
 */
  id: number;
      body?: {

/**
 * Arquivo de imagem
 */
'arquivo': Blob;
}
}

export function adicionarImagemStorie(http: HttpClient, rootUrl: string, params: AdicionarImagemStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
  const rb = new RequestBuilder(rootUrl, adicionarImagemStorie.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorieResponseDto>;
    })
  );
}

adicionarImagemStorie.PATH = '/stories/{id}/imagem';
