/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorieResponseDto } from '../../models/storie-response-dto';

export interface DestacarStorie$Params {

/**
 * ID do storie
 */
  id: number;

/**
 * ID do destaque
 */
  destaqueId: number;
}

export function destacarStorie(http: HttpClient, rootUrl: string, params: DestacarStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
  const rb = new RequestBuilder(rootUrl, destacarStorie.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('destaqueId', params.destaqueId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StorieResponseDto>;
    })
  );
}

destacarStorie.PATH = '/stories/{id}/destacar/{destaqueId}';
