/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StorieResponseDto } from '../../models/storie-response-dto';

export interface ListarStoriesDoFeed$Params {
}

export function listarStoriesDoFeed(http: HttpClient, rootUrl: string, params?: ListarStoriesDoFeed$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorieResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, listarStoriesDoFeed.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<StorieResponseDto>>;
    })
  );
}

listarStoriesDoFeed.PATH = '/stories/feed';
