/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeguidorResponseDto } from '../../models/seguidor-response-dto';

export interface AceitarSolicitacao$Params {

/**
 * ID da solicitação
 */
  id: number;
}

export function aceitarSolicitacao(http: HttpClient, rootUrl: string, params: AceitarSolicitacao$Params, context?: HttpContext): Observable<StrictHttpResponse<SeguidorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, aceitarSolicitacao.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeguidorResponseDto>;
    })
  );
}

aceitarSolicitacao.PATH = '/seguidores/solicitacoes/{id}/aceitar';
