/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AlterarNotificacoes$Params {

/**
 * ID do usuário seguido
 */
  usuarioId: number;

/**
 * Estado das notificações
 */
  ativar: boolean;
}

export function alterarNotificacoes(http: HttpClient, rootUrl: string, params: AlterarNotificacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, alterarNotificacoes.PATH, 'patch');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
    rb.query('ativar', params.ativar, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

alterarNotificacoes.PATH = '/seguidores/{usuarioId}/notificacoes';
