/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UsuarioSummaryDto } from '../../models/usuario-summary-dto';

export interface BuscarSeguidosAleatorios$Params {

/**
 * Quantidade de seguidos a retornar
 */
  limite?: number;
}

export function buscarSeguidosAleatorios(http: HttpClient, rootUrl: string, params?: BuscarSeguidosAleatorios$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UsuarioSummaryDto>>> {
  const rb = new RequestBuilder(rootUrl, buscarSeguidosAleatorios.PATH, 'get');
  if (params) {
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UsuarioSummaryDto>>;
    })
  );
}

buscarSeguidosAleatorios.PATH = '/seguidores/aleatorios';
