/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ContarSeguidoresESeguidos$Params {

/**
 * ID do usuário
 */
  usuarioId: number;
}

export function contarSeguidoresESeguidos(http: HttpClient, rootUrl: string, params: ContarSeguidoresESeguidos$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
  const rb = new RequestBuilder(rootUrl, contarSeguidoresESeguidos.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      [key: string]: number;
      }>;
    })
  );
}

contarSeguidoresESeguidos.PATH = '/seguidores/contagem/{usuarioId}';
