/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DeixarDeSeguir$Params {

/**
 * ID do usuário que deixará de seguir
 */
  usuarioId: number;
}

export function deixarDeSeguir(http: HttpClient, rootUrl: string, params: DeixarDeSeguir$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deixarDeSeguir.PATH, 'delete');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

deixarDeSeguir.PATH = '/seguidores/{usuarioId}/deixar-de-seguir';
