/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { SeguidorResponseDto } from '../../models/seguidor-response-dto';

export interface ListarSeguidores1$Params {

/**
 * ID do usuário
 */
  usuarioId: number;

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarSeguidores1(http: HttpClient, rootUrl: string, params: ListarSeguidores1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeguidorResponseDto>>> {
  const rb = new RequestBuilder(rootUrl, listarSeguidores1.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeguidorResponseDto>>;
    })
  );
}

listarSeguidores1.PATH = '/seguidores/seguidores/{usuarioId}';
