/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Page } from '../../models/page';
import { Pageable } from '../../models/pageable';
import { SeguidorResponseDto } from '../../models/seguidor-response-dto';

export interface ListarSolicitacoes$Params {

/**
 * Parâmetros de paginação (page=0, size=20)
 */
  pageable: Pageable;
}

export function listarSolicitacoes(http: HttpClient, rootUrl: string, params: ListarSolicitacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarSolicitacoes.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarSolicitacoes.PATH = '/seguidores/solicitacoes';
