/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeguidorResponseDto } from '../../models/seguidor-response-dto';

export interface SeguirUsuario$Params {

/**
 * ID do usuário a ser seguido
 */
  usuarioId: number;
}

export function seguirUsuario(http: HttpClient, rootUrl: string, params: SeguirUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<SeguidorResponseDto>> {
  const rb = new RequestBuilder(rootUrl, seguirUsuario.PATH, 'post');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeguidorResponseDto>;
    })
  );
}

seguirUsuario.PATH = '/seguidores/{usuarioId}/seguir';
