/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VerificarSeguimentoDto } from '../../models/verificar-seguimento-dto';

export interface VerificarSeguimento$Params {

/**
 * ID do usuário que está sendo seguido
 */
  usuarioId: number;
}

export function verificarSeguimento(http: HttpClient, rootUrl: string, params: VerificarSeguimento$Params, context?: HttpContext): Observable<StrictHttpResponse<VerificarSeguimentoDto>> {
  const rb = new RequestBuilder(rootUrl, verificarSeguimento.PATH, 'get');
  if (params) {
    rb.path('usuarioId', params.usuarioId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerificarSeguimentoDto>;
    })
  );
}

verificarSeguimento.PATH = '/seguidores/seguindo/{usuarioId}';
