-- V20: confianca (selo, 2FA, Pix, tipo de conta) + verificacao de e-mail.

ALTER TABLE usuario ADD COLUMN IF NOT EXISTS verificado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS email_verificado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS totp_secret VARCHAR(64);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS chave_pix VARCHAR(100);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS tipo_conta VARCHAR(20) NOT NULL DEFAULT 'PESSOAL';

CREATE TABLE IF NOT EXISTS email_verification_token (
    id BIGSERIAL PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE REFERENCES usuario (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expiracao TIMESTAMP NOT NULL,
    data_criacao TIMESTAMP NOT NULL DEFAULT NOW()
);
