/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ComentarioResponseDto } from '../../models/comentario-response-dto';

export interface CurtirComentario$Params {

/**
 * ID do comentário
 */
  id: number;
}

export function curtirComentario(http: HttpClient, rootUrl: string, params: CurtirComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<ComentarioResponseDto>> {
  const rb = new RequestBuilder(rootUrl, curtirComentario.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ComentarioResponseDto>;
    })
  );
}

curtirComentario.PATH = '/comentarios/{id}/curtir';
