/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Page } from '../../models/page';
import { Pageable } from '../../models/pageable';

export interface ListarComentariosPorPost$Params {

/**
 * ID do post
 */
  postId: number;

/**
 * Parâmetros de paginação (page=0, size=10)
 */
  pageable: Pageable;
}

export function listarComentariosPorPost(http: HttpClient, rootUrl: string, params: ListarComentariosPorPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  const rb = new RequestBuilder(rootUrl, listarComentariosPorPost.PATH, 'get');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Page>;
    })
  );
}

listarComentariosPorPost.PATH = '/comentarios/post/{postId}';
