/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { login } from '../fn/autenticacao/login';
import { Login$Params } from '../fn/autenticacao/login';
import { ativarTwoFactor } from '../fn/autenticacao/verificar-2fa';
import { confirmarTwoFactor, ConfirmarTwoFactor$Params } from '../fn/autenticacao/verificar-2fa';
import { desativarTwoFactor } from '../fn/autenticacao/verificar-2fa';
import { reenviarVerificacao } from '../fn/autenticacao/verificar-2fa';
import { verificarEmail, VerificarEmail$Params } from '../fn/autenticacao/verificar-2fa';
import { verificarTwoFactor, VerificarTwoFactor$Params } from '../fn/autenticacao/verificar-2fa';
import { recuperarSenha, RecuperarSenha$Params, redefinirSenha, RedefinirSenha$Params } from '../fn/autenticacao/recuperar-senha';
import { refreshToken } from '../fn/autenticacao/refresh-token';
import { RefreshToken$Params } from '../fn/autenticacao/refresh-token';
import { registrar } from '../fn/autenticacao/registrar';
import { Registrar$Params } from '../fn/autenticacao/registrar';
import { TokenDto } from '../models/token-dto';


/**
 * API para autenticação e registro de usuários
 */
@Injectable({ providedIn: 'root' })
export class AutenticacaoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registrar()` */
  static readonly RegistrarPath = '/auth/register';

  /**
   * Registrar usuário.
   *
   * Registra um novo usuário com foto de perfil
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrar()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  registrar$Response(params: Registrar$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return registrar(this.http, this.rootUrl, params, context);
  }

  /**
   * Registrar usuário.
   *
   * Registra um novo usuário com foto de perfil
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrar$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  registrar(params: Registrar$Params, context?: HttpContext): Observable<TokenDto> {
    return this.registrar$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }


  /** Path part for operation `refreshToken()` */
  static readonly RefreshTokenPath = '/auth/refresh-token';

  /**
   * Renovar token.
   *
   * Renova o token de acesso utilizando um refresh token válido
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refreshToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken$Response(params: RefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return refreshToken(this.http, this.rootUrl, params, context);
  }

  /**
   * Renovar token.
   *
   * Renova o token de acesso utilizando um refresh token válido
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refreshToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken(params: RefreshToken$Params, context?: HttpContext): Observable<TokenDto> {
    return this.refreshToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/auth/login';

  /**
   * Autenticar usuário.
   *
   * Autentica o usuário com email e senha e retorna um token de acesso
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * Autenticar usuário.
   *
   * Autentica o usuário com email e senha e retorna um token de acesso
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<TokenDto> {
    return this.login$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `recuperarSenha()` */
  static readonly RecuperarSenhaPath = '/auth/recuperar-senha';

  /**
   * Solicitar recuperação de senha.
   *
   * Resposta sempre genérica para não revelar se o e-mail existe
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `recuperarSenha()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  recuperarSenha$Response(params: RecuperarSenha$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return recuperarSenha(this.http, this.rootUrl, params, context);
  }

  /**
   * Solicitar recuperação de senha.
   *
   * Resposta sempre genérica para não revelar se o e-mail existe
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `recuperarSenha$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  recuperarSenha(params: RecuperarSenha$Params, context?: HttpContext): Observable<void> {
    return this.recuperarSenha$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `redefinirSenha()` */
  static readonly RedefinirSenhaPath = '/auth/redefinir-senha';

  /**
   * Redefinir senha.
   *
   * Troca a senha com token single-use de 1h
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `redefinirSenha()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  redefinirSenha$Response(params: RedefinirSenha$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return redefinirSenha(this.http, this.rootUrl, params, context);
  }

  /**
   * Redefinir senha.
   *
   * Troca a senha com token single-use de 1h
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `redefinirSenha$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  redefinirSenha(params: RedefinirSenha$Params, context?: HttpContext): Observable<void> {
    return this.redefinirSenha$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `verificarTwoFactor()` */
  static readonly VerificarTwoFactorPath = '/auth/2fa/verificar';

  /**
   * Concluir login com 2FA.
   *
   * Segunda etapa: código do app autenticador
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificarTwoFactor()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificarTwoFactor$Response(params: VerificarTwoFactor$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return verificarTwoFactor(this.http, this.rootUrl, params, context);
  }

  /**
   * Concluir login com 2FA.
   *
   * Segunda etapa: código do app autenticador
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificarTwoFactor$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  verificarTwoFactor(params: VerificarTwoFactor$Params, context?: HttpContext): Observable<TokenDto> {
    return this.verificarTwoFactor$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `ativarTwoFactor()` */
  static readonly AtivarTwoFactorPath = '/auth/2fa/ativar';

  /**
   * Iniciar ativação do 2FA.
   *
   * Retorna segredo + URI para o app autenticador
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `ativarTwoFactor()` instead.
   *
   * This method doesn't expect any request body.
   */
  ativarTwoFactor$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return ativarTwoFactor(this.http, this.rootUrl, context);
  }

  /**
   * Iniciar ativação do 2FA.
   *
   * Retorna segredo + URI para o app autenticador
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `ativarTwoFactor$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  ativarTwoFactor(context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.ativarTwoFactor$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

  /** Path part for operation `confirmarTwoFactor()` */
  static readonly ConfirmarTwoFactorPath = '/auth/2fa/confirmar';

  /**
   * Confirmar ativação do 2FA.
   *
   * Valida o código e ativa
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `confirmarTwoFactor()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmarTwoFactor$Response(params: ConfirmarTwoFactor$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return confirmarTwoFactor(this.http, this.rootUrl, params, context);
  }

  /**
   * Confirmar ativação do 2FA.
   *
   * Valida o código e ativa
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `confirmarTwoFactor$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmarTwoFactor(params: ConfirmarTwoFactor$Params, context?: HttpContext): Observable<void> {
    return this.confirmarTwoFactor$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `desativarTwoFactor()` */
  static readonly DesativarTwoFactorPath = '/auth/2fa';

  /**
   * Desativar 2FA.
   *
   * Remove a autenticação em dois fatores
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `desativarTwoFactor()` instead.
   *
   * This method doesn't expect any request body.
   */
  desativarTwoFactor$Response(context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return desativarTwoFactor(this.http, this.rootUrl, context);
  }

  /**
   * Desativar 2FA.
   *
   * Remove a autenticação em dois fatores
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `desativarTwoFactor$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  desativarTwoFactor(context?: HttpContext): Observable<void> {
    return this.desativarTwoFactor$Response(context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `reenviarVerificacao()` */
  static readonly ReenviarVerificacaoPath = '/auth/verificar-email/reenviar';

  /**
   * Reenviar verificação.
   *
   * Novo link de 24h para o autenticado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reenviarVerificacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  reenviarVerificacao$Response(context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return reenviarVerificacao(this.http, this.rootUrl, context);
  }

  /**
   * Reenviar verificação.
   *
   * Novo link de 24h para o autenticado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reenviarVerificacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  reenviarVerificacao(context?: HttpContext): Observable<void> {
    return this.reenviarVerificacao$Response(context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `verificarEmail()` */
  static readonly VerificarEmailPath = '/auth/verificar-email';

  /**
   * Verificar e-mail.
   *
   * Confirma o token single-use de 24h
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificarEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificarEmail$Response(params: VerificarEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return verificarEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * Verificar e-mail.
   *
   * Confirma o token single-use de 24h
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificarEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificarEmail(params: VerificarEmail$Params, context?: HttpContext): Observable<void> {
    return this.verificarEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
