/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { login } from '../fn/autenticacao/login';
import { Login$Params } from '../fn/autenticacao/login';
import { refreshToken } from '../fn/autenticacao/refresh-token';
import { RefreshToken$Params } from '../fn/autenticacao/refresh-token';
import { registrar } from '../fn/autenticacao/registrar';
import { Registrar$Params } from '../fn/autenticacao/registrar';
import { TokenDto } from '../models/token-dto';


/**
 * Operações relacionadas à autenticação
 */
@Injectable({ providedIn: 'root' })
export class AutenticacaoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registrar()` */
  static readonly RegistrarPath = '/auth/register';

  /**
   * Registrar novo usuário.
   *
   * Cria um novo usuário no sistema e retorna um token de autenticação
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrar()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrar$Response(params: Registrar$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return registrar(this.http, this.rootUrl, params, context);
  }

  /**
   * Registrar novo usuário.
   *
   * Cria um novo usuário no sistema e retorna um token de autenticação
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrar$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registrar(params: Registrar$Params, context?: HttpContext): Observable<TokenDto> {
    return this.registrar$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `refreshToken()` */
  static readonly RefreshTokenPath = '/auth/refresh-token';

  /**
   * Renovar token.
   *
   * Renova o token de acesso utilizando um refresh token válido
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refreshToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken$Response(params: RefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return refreshToken(this.http, this.rootUrl, params, context);
  }

  /**
   * Renovar token.
   *
   * Renova o token de acesso utilizando um refresh token válido
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refreshToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken(params: RefreshToken$Params, context?: HttpContext): Observable<TokenDto> {
    return this.refreshToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/auth/login';

  /**
   * Autenticar usuário.
   *
   * Autentica o usuário com email e senha e retorna um token de acesso
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * Autenticar usuário.
   *
   * Autentica o usuário com email e senha e retorna um token de acesso
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<TokenDto> {
    return this.login$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

}
