/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { buscar, Buscar$Params } from '../fn/buscar';
import { BuscarResponseDto } from '../models/buscar-response-dto';


/**
 * Busca global
 */
@Injectable({ providedIn: 'root' })
export class BuscarService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `buscar()` */
  static readonly BuscarPath = '/buscar';

  /**
   * Busca global.
   *
   * Pessoas + posts (privacidade aplicada) + hashtags
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscar()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscar$Response(params: Buscar$Params, context?: HttpContext): Observable<StrictHttpResponse<BuscarResponseDto>> {
    return buscar(this.http, this.rootUrl, params, context);
  }

  /**
   * Busca global.
   *
   * Pessoas + posts (privacidade aplicada) + hashtags
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscar$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscar(params: Buscar$Params, context?: HttpContext): Observable<BuscarResponseDto> {
    return this.buscar$Response(params, context).pipe(
      map((r: StrictHttpResponse<BuscarResponseDto>): BuscarResponseDto => r.body)
    );
  }

}
