/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { atualizarComentario } from '../fn/comentarios/atualizar-comentario';
import { AtualizarComentario$Params } from '../fn/comentarios/atualizar-comentario';
import { ComentarioResponseDto } from '../models/comentario-response-dto';
import { criarComentario } from '../fn/comentarios/criar-comentario';
import { CriarComentario$Params } from '../fn/comentarios/criar-comentario';
import { curtirComentario } from '../fn/comentarios/curtir-comentario';
import { CurtirComentario$Params } from '../fn/comentarios/curtir-comentario';
import { descurtirComentario } from '../fn/comentarios/descurtir-comentario';
import { DescurtirComentario$Params } from '../fn/comentarios/descurtir-comentario';
import { excluirComentario } from '../fn/comentarios/excluir-comentario';
import { ExcluirComentario$Params } from '../fn/comentarios/excluir-comentario';
import { listarComentariosPorPost } from '../fn/comentarios/listar-comentarios-por-post';
import { ListarComentariosPorPost$Params } from '../fn/comentarios/listar-comentarios-por-post';
import { listarRespostasPorComentario } from '../fn/comentarios/listar-respostas-por-comentario';
import { ListarRespostasPorComentario$Params } from '../fn/comentarios/listar-respostas-por-comentario';
import { Page } from '../models/page';


/**
 * Gerenciamento de comentários
 */
@Injectable({ providedIn: 'root' })
export class ComentariosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `atualizarComentario()` */
  static readonly AtualizarComentarioPath = '/comentarios/{id}';

  /**
   * Atualizar comentário.
   *
   * Atualiza o texto de um comentário existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarComentario()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarComentario$Response(params: AtualizarComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<ComentarioResponseDto>> {
    return atualizarComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Atualizar comentário.
   *
   * Atualiza o texto de um comentário existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarComentario$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarComentario(params: AtualizarComentario$Params, context?: HttpContext): Observable<ComentarioResponseDto> {
    return this.atualizarComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<ComentarioResponseDto>): ComentarioResponseDto => r.body)
    );
  }

  /** Path part for operation `excluirComentario()` */
  static readonly ExcluirComentarioPath = '/comentarios/{id}';

  /**
   * Excluir comentário.
   *
   * Exclui um comentário existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirComentario()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirComentario$Response(params: ExcluirComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir comentário.
   *
   * Exclui um comentário existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirComentario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirComentario(params: ExcluirComentario$Params, context?: HttpContext): Observable<void> {
    return this.excluirComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `criarComentario()` */
  static readonly CriarComentarioPath = '/comentarios';

  /**
   * Criar comentário.
   *
   * Cria um novo comentário em um post ou como resposta a outro comentário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `criarComentario()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarComentario$Response(params: CriarComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<ComentarioResponseDto>> {
    return criarComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Criar comentário.
   *
   * Cria um novo comentário em um post ou como resposta a outro comentário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `criarComentario$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarComentario(params: CriarComentario$Params, context?: HttpContext): Observable<ComentarioResponseDto> {
    return this.criarComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<ComentarioResponseDto>): ComentarioResponseDto => r.body)
    );
  }

  /** Path part for operation `curtirComentario()` */
  static readonly CurtirComentarioPath = '/comentarios/{id}/curtir';

  /**
   * Curtir comentário.
   *
   * Adiciona uma curtida a um comentário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `curtirComentario()` instead.
   *
   * This method doesn't expect any request body.
   */
  curtirComentario$Response(params: CurtirComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<ComentarioResponseDto>> {
    return curtirComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Curtir comentário.
   *
   * Adiciona uma curtida a um comentário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `curtirComentario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  curtirComentario(params: CurtirComentario$Params, context?: HttpContext): Observable<ComentarioResponseDto> {
    return this.curtirComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<ComentarioResponseDto>): ComentarioResponseDto => r.body)
    );
  }

  /** Path part for operation `listarRespostasPorComentario()` */
  static readonly ListarRespostasPorComentarioPath = '/comentarios/{id}/respostas';

  /**
   * Listar respostas de um comentário.
   *
   * Retorna as respostas de um comentário específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarRespostasPorComentario()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarRespostasPorComentario$Response(params: ListarRespostasPorComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return listarRespostasPorComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar respostas de um comentário.
   *
   * Retorna as respostas de um comentário específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarRespostasPorComentario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarRespostasPorComentario(params: ListarRespostasPorComentario$Params, context?: HttpContext): Observable<string> {
    return this.listarRespostasPorComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `listarComentariosPorPost()` */
  static readonly ListarComentariosPorPostPath = '/comentarios/post/{postId}';

  /**
   * Listar comentários de um post.
   *
   * Retorna os comentários principais de um post
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarComentariosPorPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarComentariosPorPost$Response(params: ListarComentariosPorPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarComentariosPorPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar comentários de um post.
   *
   * Retorna os comentários principais de um post
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarComentariosPorPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarComentariosPorPost(params: ListarComentariosPorPost$Params, context?: HttpContext): Observable<Page> {
    return this.listarComentariosPorPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `descurtirComentario()` */
  static readonly DescurtirComentarioPath = '/comentarios/{id}/descurtir';

  /**
   * Remover curtida.
   *
   * Remove a curtida de um comentário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `descurtirComentario()` instead.
   *
   * This method doesn't expect any request body.
   */
  descurtirComentario$Response(params: DescurtirComentario$Params, context?: HttpContext): Observable<StrictHttpResponse<ComentarioResponseDto>> {
    return descurtirComentario(this.http, this.rootUrl, params, context);
  }

  /**
   * Remover curtida.
   *
   * Remove a curtida de um comentário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `descurtirComentario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  descurtirComentario(params: DescurtirComentario$Params, context?: HttpContext): Observable<ComentarioResponseDto> {
    return this.descurtirComentario$Response(params, context).pipe(
      map((r: StrictHttpResponse<ComentarioResponseDto>): ComentarioResponseDto => r.body)
    );
  }

}
