/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { contarMensagensNaoLidas } from '../fn/conversas';
import { enviarMensagem, EnviarMensagem$Params } from '../fn/conversas';
import { iniciarConversa, IniciarConversa$Params } from '../fn/conversas';
import { listarConversas, ListarConversas$Params } from '../fn/conversas';
import { listarMensagens, ListarMensagens$Params } from '../fn/conversas';
import { ConversaResponseDto } from '../models/conversa-response-dto';
import { MensagemResponseDto } from '../models/mensagem-response-dto';
import { Page } from '../models/page';


/**
 * Mensagens diretas 1:1
 */
@Injectable({ providedIn: 'root' })
export class ConversasService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `iniciarConversa()` */
  static readonly IniciarConversaPath = '/conversas/iniciar/{usuarioId}';

  /**
   * Iniciar ou obter conversa.
   *
   * Abre a conversa 1:1 (idempotente por par)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `iniciarConversa()` instead.
   *
   * This method doesn't expect any request body.
   */
  iniciarConversa$Response(params: IniciarConversa$Params, context?: HttpContext): Observable<StrictHttpResponse<ConversaResponseDto>> {
    return iniciarConversa(this.http, this.rootUrl, params, context);
  }

  /**
   * Iniciar ou obter conversa.
   *
   * Abre a conversa 1:1 (idempotente por par)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `iniciarConversa$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  iniciarConversa(params: IniciarConversa$Params, context?: HttpContext): Observable<ConversaResponseDto> {
    return this.iniciarConversa$Response(params, context).pipe(
      map((r: StrictHttpResponse<ConversaResponseDto>): ConversaResponseDto => r.body)
    );
  }

  /** Path part for operation `listarConversas()` */
  static readonly ListarConversasPath = '/conversas';

  /**
   * Listar conversas.
   *
   * Conversas do usuário ordenadas por atividade
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarConversas()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarConversas$Response(params: ListarConversas$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarConversas(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar conversas.
   *
   * Conversas do usuário ordenadas por atividade
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarConversas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarConversas(params: ListarConversas$Params, context?: HttpContext): Observable<Page> {
    return this.listarConversas$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarMensagens()` */
  static readonly ListarMensagensPath = '/conversas/{id}/mensagens';

  /**
   * Listar mensagens.
   *
   * Marca como lidas ao listar
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarMensagens()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarMensagens$Response(params: ListarMensagens$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarMensagens(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar mensagens.
   *
   * Marca como lidas ao listar
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarMensagens$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarMensagens(params: ListarMensagens$Params, context?: HttpContext): Observable<Page> {
    return this.listarMensagens$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `enviarMensagem()` */
  static readonly EnviarMensagemPath = '/conversas/{id}/mensagens';

  /**
   * Enviar mensagem.
   *
   * Envia texto (máx. 1000 caracteres)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `enviarMensagem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enviarMensagem$Response(params: EnviarMensagem$Params, context?: HttpContext): Observable<StrictHttpResponse<MensagemResponseDto>> {
    return enviarMensagem(this.http, this.rootUrl, params, context);
  }

  /**
   * Enviar mensagem.
   *
   * Envia texto (máx. 1000 caracteres)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `enviarMensagem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  enviarMensagem(params: EnviarMensagem$Params, context?: HttpContext): Observable<MensagemResponseDto> {
    return this.enviarMensagem$Response(params, context).pipe(
      map((r: StrictHttpResponse<MensagemResponseDto>): MensagemResponseDto => r.body)
    );
  }

  /** Path part for operation `contarMensagensNaoLidas()` */
  static readonly ContarMensagensNaoLidasPath = '/conversas/nao-lidas/contagem';

  /**
   * Contar não lidas.
   *
   * Badge de mensagens
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contarMensagensNaoLidas()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarMensagensNaoLidas$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return contarMensagensNaoLidas(this.http, this.rootUrl, context);
  }

  /**
   * Contar não lidas.
   *
   * Badge de mensagens
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contarMensagensNaoLidas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarMensagensNaoLidas(context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.contarMensagensNaoLidas$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

}
