/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adicionarCapaDestaque } from '../fn/destaques/adicionar-capa-destaque';
import { AdicionarCapaDestaque$Params } from '../fn/destaques/adicionar-capa-destaque';
import { atualizarDestaque } from '../fn/destaques/atualizar-destaque';
import { AtualizarDestaque$Params } from '../fn/destaques/atualizar-destaque';
import { buscarDestaquePorId } from '../fn/destaques/buscar-destaque-por-id';
import { BuscarDestaquePorId$Params } from '../fn/destaques/buscar-destaque-por-id';
import { contarStoriesPorDestaque } from '../fn/destaques/contar-stories-por-destaque';
import { ContarStoriesPorDestaque$Params } from '../fn/destaques/contar-stories-por-destaque';
import { criarDestaque } from '../fn/destaques/criar-destaque';
import { CriarDestaque$Params } from '../fn/destaques/criar-destaque';
import { DestaqueResponseDto } from '../models/destaque-response-dto';
import { DestaqueSummaryDto } from '../models/destaque-summary-dto';
import { excluirDestaque } from '../fn/destaques/excluir-destaque';
import { ExcluirDestaque$Params } from '../fn/destaques/excluir-destaque';
import { listarDestaquesPorUsername, ListarDestaquesPorUsername$Params } from '../fn/destaques/listar-destaques';
import { listarStoriesPorDestaque, ListarStoriesPorDestaque$Params } from '../fn/destaques/listar-stories-por-destaque';
import { ContagemStoriesDto } from '../models/contagem-stories-dto';
import { Page } from '../models/page';
import { StorieResponseDto } from '../models/storie-response-dto';


/**
 * Operações relacionadas a destaques de stories
 */
@Injectable({ providedIn: 'root' })
export class DestaquesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `buscarDestaquePorId()` */
  static readonly BuscarDestaquePorIdPath = '/destaques/{id}';

  /**
   * Buscar destaque por ID.
   *
   * Busca um destaque específico pelo seu ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarDestaquePorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarDestaquePorId$Response(params: BuscarDestaquePorId$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
    return buscarDestaquePorId(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar destaque por ID.
   *
   * Busca um destaque específico pelo seu ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarDestaquePorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarDestaquePorId(params: BuscarDestaquePorId$Params, context?: HttpContext): Observable<DestaqueResponseDto> {
    return this.buscarDestaquePorId$Response(params, context).pipe(
      map((r: StrictHttpResponse<DestaqueResponseDto>): DestaqueResponseDto => r.body)
    );
  }

  /** Path part for operation `atualizarDestaque()` */
  static readonly AtualizarDestaquePath = '/destaques/{id}';

  /**
   * Atualizar destaque.
   *
   * Atualiza informações de um destaque existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarDestaque()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarDestaque$Response(params: AtualizarDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
    return atualizarDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Atualizar destaque.
   *
   * Atualiza informações de um destaque existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarDestaque$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarDestaque(params: AtualizarDestaque$Params, context?: HttpContext): Observable<DestaqueResponseDto> {
    return this.atualizarDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<DestaqueResponseDto>): DestaqueResponseDto => r.body)
    );
  }

  /** Path part for operation `excluirDestaque()` */
  static readonly ExcluirDestaquePath = '/destaques/{id}';

  /**
   * Excluir destaque.
   *
   * Remove um destaque existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirDestaque()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirDestaque$Response(params: ExcluirDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir destaque.
   *
   * Remove um destaque existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirDestaque$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirDestaque(params: ExcluirDestaque$Params, context?: HttpContext): Observable<void> {
    return this.excluirDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

 /** Path part for operation `listarDestaquesPorUsername()` */
static readonly ListarDestaquesPorUsernamePath = '/destaques/usuario/{username}';

/**
 * Listar destaques por username.
 *
 * Lista todos os destaques criados por um usuário específico
 *
 * This method provides access to the full `HttpResponse`, allowing access to response headers.
 * To access only the response body, use `listarDestaquesPorUsername()` instead.
 *
 * This method doesn't expect any request body.
 */
listarDestaquesPorUsername$Response(params: ListarDestaquesPorUsername$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
  return listarDestaquesPorUsername(this.http, this.rootUrl, params, context);
}

/**
 * Listar destaques por username.
 *
 * Lista todos os destaques criados por um usuário específico
 *
 * This method provides access only to the response body.
 * To access the full response (for headers, for example), `listarDestaquesPorUsername$Response()` instead.
 *
 * This method doesn't expect any request body.
 */
listarDestaquesPorUsername(params: ListarDestaquesPorUsername$Params, context?: HttpContext): Observable<Page> {
  return this.listarDestaquesPorUsername$Response(params, context).pipe(
    map((r: StrictHttpResponse<Page>): Page => r.body)
  );
}

  /** Path part for operation `criarDestaque()` */
  static readonly CriarDestaquePath = '/destaques';

  /**
   * Criar um novo destaque.
   *
   * Cria um novo destaque para agrupar stories
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `criarDestaque()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  criarDestaque$Response(params?: CriarDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
    return criarDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Criar um novo destaque.
   *
   * Cria um novo destaque para agrupar stories
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `criarDestaque$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  criarDestaque(params?: CriarDestaque$Params, context?: HttpContext): Observable<DestaqueResponseDto> {
    return this.criarDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<DestaqueResponseDto>): DestaqueResponseDto => r.body)
    );
  }

  /** Path part for operation `adicionarCapaDestaque()` */
  static readonly AdicionarCapaDestaquePath = '/destaques/{id}/capa';

  /**
   * Adicionar capa ao destaque.
   *
   * Adiciona ou atualiza a imagem de capa do destaque
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adicionarCapaDestaque()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adicionarCapaDestaque$Response(params: AdicionarCapaDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<DestaqueResponseDto>> {
    return adicionarCapaDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Adicionar capa ao destaque.
   *
   * Adiciona ou atualiza a imagem de capa do destaque
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adicionarCapaDestaque$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adicionarCapaDestaque(params: AdicionarCapaDestaque$Params, context?: HttpContext): Observable<DestaqueResponseDto> {
    return this.adicionarCapaDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<DestaqueResponseDto>): DestaqueResponseDto => r.body)
    );
  }

  /** Path part for operation `listarStoriesPorDestaque()` */
  static readonly ListarStoriesPorDestaquePath = '/destaques/{id}/stories';

  /**
   * Listar stories de um destaque.
   *
   * Lista todas as stories presentes em um destaque específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarStoriesPorDestaque()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesPorDestaque$Response(params: ListarStoriesPorDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarStoriesPorDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar stories de um destaque.
   *
   * Lista todas as stories presentes em um destaque específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarStoriesPorDestaque$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesPorDestaque(params: ListarStoriesPorDestaque$Params, context?: HttpContext): Observable<Page> {
    return this.listarStoriesPorDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `contarStoriesPorDestaque()` */
  static readonly ContarStoriesPorDestaquePath = '/destaques/{id}/contagem-stories';

  /**
   * Contar stories em um destaque.
   *
   * Retorna o número de stories em um destaque específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contarStoriesPorDestaque()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarStoriesPorDestaque$Response(params: ContarStoriesPorDestaque$Params, context?: HttpContext): Observable<StrictHttpResponse<ContagemStoriesDto>> {
    return contarStoriesPorDestaque(this.http, this.rootUrl, params, context);
  }

  /**
   * Contar stories em um destaque.
   *
   * Retorna o número de stories em um destaque específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contarStoriesPorDestaque$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarStoriesPorDestaque(params: ContarStoriesPorDestaque$Params, context?: HttpContext): Observable<ContagemStoriesDto> {
    return this.contarStoriesPorDestaque$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContagemStoriesDto>): ContagemStoriesDto => r.body)
    );
  }

}
