/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { criarEnquete, CriarEnquete$Params } from '../fn/enquetes';
import { excluirEnquete, ExcluirEnquete$Params } from '../fn/enquetes';
import { votarEnquete, VotarEnquete$Params } from '../fn/enquetes';
import { PollResponseDto } from '../models/poll-response-dto';


/**
 * Enquetes em posts e stories
 */
@Injectable({ providedIn: 'root' })
export class EnquetesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `criarEnquete()` */
  static readonly CriarEnquetePath = '/enquetes';

  /**
   * Criar enquete.
   *
   * Anexa enquete de 2-4 opções a um post ou storie do autor
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `criarEnquete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarEnquete$Response(params: CriarEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResponseDto>> {
    return criarEnquete(this.http, this.rootUrl, params, context);
  }

  /**
   * Criar enquete.
   *
   * Anexa enquete de 2-4 opções a um post ou storie do autor
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `criarEnquete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarEnquete(params: CriarEnquete$Params, context?: HttpContext): Observable<PollResponseDto> {
    return this.criarEnquete$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResponseDto>): PollResponseDto => r.body)
    );
  }

  /** Path part for operation `votarEnquete()` */
  static readonly VotarEnquetePath = '/enquetes/{id}/votar';

  /**
   * Votar.
   *
   * Um voto por usuário (idempotente via 409)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `votarEnquete()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  votarEnquete$Response(params: VotarEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResponseDto>> {
    return votarEnquete(this.http, this.rootUrl, params, context);
  }

  /**
   * Votar.
   *
   * Um voto por usuário (idempotente via 409)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `votarEnquete$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  votarEnquete(params: VotarEnquete$Params, context?: HttpContext): Observable<PollResponseDto> {
    return this.votarEnquete$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResponseDto>): PollResponseDto => r.body)
    );
  }

  /** Path part for operation `excluirEnquete()` */
  static readonly ExcluirEnquetePath = '/enquetes/{id}';

  /**
   * Excluir enquete.
   *
   * Só o autor exclui
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirEnquete()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirEnquete$Response(params: ExcluirEnquete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirEnquete(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir enquete.
   *
   * Só o autor exclui
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirEnquete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirEnquete(params: ExcluirEnquete$Params, context?: HttpContext): Observable<void> {
    return this.excluirEnquete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
