/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { buscarHashtags } from '../fn/hashtags/buscar-hashtags';
import { BuscarHashtags$Params } from '../fn/hashtags/buscar-hashtags';
import { buscarPorNome } from '../fn/hashtags/buscar-por-nome';
import { BuscarPorNome$Params } from '../fn/hashtags/buscar-por-nome';
import { HashtagResponseDto } from '../models/hashtag-response-dto';
import { HashtagSummaryDto } from '../models/hashtag-summary-dto';
import { listarHashtagsPopulares } from '../fn/hashtags/listar-hashtags-populares';
import { ListarHashtagsPopulares$Params } from '../fn/hashtags/listar-hashtags-populares';
import { listarHashtagsPorPostId } from '../fn/hashtags/listar-hashtags-por-post-id';
import { ListarHashtagsPorPostId$Params } from '../fn/hashtags/listar-hashtags-por-post-id';
import { PageHashtagSummaryDto } from '../models/page-hashtag-summary-dto';
import { sugerirHashtags } from '../fn/hashtags/sugerir-hashtags';
import { SugerirHashtags$Params } from '../fn/hashtags/sugerir-hashtags';


/**
 * Operações relacionadas a hashtags
 */
@Injectable({ providedIn: 'root' })
export class HashtagsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `buscarPorNome()` */
  static readonly BuscarPorNomePath = '/hashtags/{nome}';

  /**
   * Buscar hashtag por nome.
   *
   * Busca uma hashtag específica pelo seu nome
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarPorNome()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarPorNome$Response(params: BuscarPorNome$Params, context?: HttpContext): Observable<StrictHttpResponse<HashtagResponseDto>> {
    return buscarPorNome(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar hashtag por nome.
   *
   * Busca uma hashtag específica pelo seu nome
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarPorNome$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarPorNome(params: BuscarPorNome$Params, context?: HttpContext): Observable<HashtagResponseDto> {
    return this.buscarPorNome$Response(params, context).pipe(
      map((r: StrictHttpResponse<HashtagResponseDto>): HashtagResponseDto => r.body)
    );
  }

  /** Path part for operation `sugerirHashtags()` */
  static readonly SugerirHashtagsPath = '/hashtags/sugestoes';

  /**
   * Sugerir hashtags.
   *
   * Sugere hashtags com base em um termo de busca
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sugerirHashtags()` instead.
   *
   * This method doesn't expect any request body.
   */
  sugerirHashtags$Response(params: SugerirHashtags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HashtagSummaryDto>>> {
    return sugerirHashtags(this.http, this.rootUrl, params, context);
  }

  /**
   * Sugerir hashtags.
   *
   * Sugere hashtags com base em um termo de busca
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sugerirHashtags$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  sugerirHashtags(params: SugerirHashtags$Params, context?: HttpContext): Observable<Array<HashtagSummaryDto>> {
    return this.sugerirHashtags$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HashtagSummaryDto>>): Array<HashtagSummaryDto> => r.body)
    );
  }

  /** Path part for operation `listarHashtagsPorPostId()` */
  static readonly ListarHashtagsPorPostIdPath = '/hashtags/post/{postId}';

  /**
   * Listar hashtags por post.
   *
   * Lista todas as hashtags associadas a um post específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarHashtagsPorPostId()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarHashtagsPorPostId$Response(params: ListarHashtagsPorPostId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HashtagSummaryDto>>> {
    return listarHashtagsPorPostId(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar hashtags por post.
   *
   * Lista todas as hashtags associadas a um post específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarHashtagsPorPostId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarHashtagsPorPostId(params: ListarHashtagsPorPostId$Params, context?: HttpContext): Observable<Array<HashtagSummaryDto>> {
    return this.listarHashtagsPorPostId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<HashtagSummaryDto>>): Array<HashtagSummaryDto> => r.body)
    );
  }

  /** Path part for operation `listarHashtagsPopulares()` */
  static readonly ListarHashtagsPopularesPath = '/hashtags/populares';

  /**
   * Listar hashtags populares.
   *
   * Lista as hashtags mais utilizadas na plataforma
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarHashtagsPopulares()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarHashtagsPopulares$Response(params: ListarHashtagsPopulares$Params, context?: HttpContext): Observable<StrictHttpResponse<PageHashtagSummaryDto>> {
    return listarHashtagsPopulares(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar hashtags populares.
   *
   * Lista as hashtags mais utilizadas na plataforma
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarHashtagsPopulares$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarHashtagsPopulares(params: ListarHashtagsPopulares$Params, context?: HttpContext): Observable<PageHashtagSummaryDto> {
    return this.listarHashtagsPopulares$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageHashtagSummaryDto>): PageHashtagSummaryDto => r.body)
    );
  }

  /** Path part for operation `buscarHashtags()` */
  static readonly BuscarHashtagsPath = '/hashtags/buscar';

  /**
   * Buscar hashtags.
   *
   * Busca hashtags que contenham o termo especificado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarHashtags()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarHashtags$Response(params: BuscarHashtags$Params, context?: HttpContext): Observable<StrictHttpResponse<PageHashtagSummaryDto>> {
    return buscarHashtags(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar hashtags.
   *
   * Busca hashtags que contenham o termo especificado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarHashtags$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarHashtags(params: BuscarHashtags$Params, context?: HttpContext): Observable<PageHashtagSummaryDto> {
    return this.buscarHashtags$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageHashtagSummaryDto>): PageHashtagSummaryDto => r.body)
    );
  }

}
