/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { bloquear, Bloquear$Params } from '../fn/moderacao';
import { denunciar, Denunciar$Params } from '../fn/moderacao';
import { desbloquear, Desbloquear$Params } from '../fn/moderacao';
import { listarBloqueios, ListarBloqueios$Params } from '../fn/moderacao';
import { listarFila, ListarFila$Params } from '../fn/moderacao';
import { resolverDenuncia, ResolverDenuncia$Params, DenunciaDto } from '../fn/moderacao';
import { verificarBloqueio, VerificarBloqueio$Params, BloqueioStatus } from '../fn/moderacao';
import { Page } from '../models/page';


/**
 * Moderação: denúncias e bloqueios
 */
@Injectable({ providedIn: 'root' })
export class ModeracaoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `denunciar()` */
  static readonly DenunciarPath = '/moderacao/denuncias';

  /**
   * Denunciar conteúdo.
   *
   * Abre uma denúncia (idempotente por autor+alvo)
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `denunciar()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciar$Response(params: Denunciar$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return denunciar(this.http, this.rootUrl, params, context);
  }

  /**
   * Denunciar conteúdo.
   *
   * Abre uma denúncia (idempotente por autor+alvo)
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `denunciar$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  denunciar(params: Denunciar$Params, context?: HttpContext): Observable<void> {
    return this.denunciar$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bloquear()` */
  static readonly BloquearPath = '/moderacao/bloqueios/{usuarioId}';

  /**
   * Bloquear usuário.
   *
   * Bloqueia e rompe o vínculo nos dois sentidos
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bloquear()` instead.
   *
   * This method doesn't expect any request body.
   */
  bloquear$Response(params: Bloquear$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bloquear(this.http, this.rootUrl, params, context);
  }

  /**
   * Bloquear usuário.
   *
   * Bloqueia e rompe o vínculo nos dois sentidos
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bloquear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bloquear(params: Bloquear$Params, context?: HttpContext): Observable<void> {
    return this.bloquear$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `desbloquear()` */
  static readonly DesbloquearPath = '/moderacao/bloqueios/{usuarioId}';

  /**
   * Desbloquear usuário.
   *
   * Remove o bloqueio
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `desbloquear()` instead.
   *
   * This method doesn't expect any request body.
   */
  desbloquear$Response(params: Desbloquear$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return desbloquear(this.http, this.rootUrl, params, context);
  }

  /**
   * Desbloquear usuário.
   *
   * Remove o bloqueio
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `desbloquear$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  desbloquear(params: Desbloquear$Params, context?: HttpContext): Observable<void> {
    return this.desbloquear$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `verificarBloqueio()` */
  static readonly VerificarBloqueioPath = '/moderacao/bloqueios/verificar/{usuarioId}';

  /**
   * Verificar bloqueio.
   *
   * Diz se o autenticado bloqueou o usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body.
   *
   * This method doesn't expect any request body.
   */
  verificarBloqueio$Response(params: VerificarBloqueio$Params, context?: HttpContext): Observable<StrictHttpResponse<BloqueioStatus>> {
    return verificarBloqueio(this.http, this.rootUrl, params, context);
  }

  /**
   * Verificar bloqueio.
   *
   * Diz se o autenticado bloqueou o usuário
   *
   * This method provides access only to the response body.
   *
   * This method doesn't expect any request body.
   */
  verificarBloqueio(params: VerificarBloqueio$Params, context?: HttpContext): Observable<BloqueioStatus> {
    return this.verificarBloqueio$Response(params, context).pipe(
      map((r: StrictHttpResponse<BloqueioStatus>): BloqueioStatus => r.body)
    );
  }

  /** Path part for operation `listarBloqueios()` */
  static readonly ListarBloqueiosPath = '/moderacao/bloqueios';

  /**
   * Listar bloqueios.
   *
   * Usuários bloqueados pelo autenticado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarBloqueios()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarBloqueios$Response(params: ListarBloqueios$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarBloqueios(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar bloqueios.
   *
   * Usuários bloqueados pelo autenticado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarBloqueios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarBloqueios(params: ListarBloqueios$Params, context?: HttpContext): Observable<Page> {
    return this.listarBloqueios$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarFila()` */
  static readonly ListarFilaPath = '/moderacao/denuncias';

  /**
   * Fila de moderação (ADMIN).
   *
   * Todas as denúncias, filtráveis por status
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarFila()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarFila$Response(params: ListarFila$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarFila(this.http, this.rootUrl, params, context);
  }

  /**
   * Fila de moderação (ADMIN).
   *
   * Todas as denúncias, filtráveis por status
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarFila$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarFila(params: ListarFila$Params, context?: HttpContext): Observable<Page> {
    return this.listarFila$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `resolverDenuncia()` */
  static readonly ResolverDenunciaPath = '/moderacao/denuncias/{id}';

  /**
   * Resolver denúncia (ADMIN).
   *
   * Move para EM_ANALISE, RESOLVIDA ou REJEITADA
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resolverDenuncia()` instead.
   *
   * This method doesn't expect any request body.
   */
  resolverDenuncia$Response(params: ResolverDenuncia$Params, context?: HttpContext): Observable<StrictHttpResponse<DenunciaDto>> {
    return resolverDenuncia(this.http, this.rootUrl, params, context);
  }

  /**
   * Resolver denúncia (ADMIN).
   *
   * Move para EM_ANALISE, RESOLVIDA ou REJEITADA
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resolverDenuncia$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resolverDenuncia(params: ResolverDenuncia$Params, context?: HttpContext): Observable<DenunciaDto> {
    return this.resolverDenuncia$Response(params, context).pipe(
      map((r: StrictHttpResponse<DenunciaDto>): DenunciaDto => r.body)
    );
  }

}
