/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { contarNaoLidas } from '../fn/notificacoes';
import { deletarNotificacao, DeletarNotificacao$Params } from '../fn/notificacoes';
import { listarNotificacoes, ListarNotificacoes$Params } from '../fn/notificacoes';
import { marcarComoVisualizada, MarcarComoVisualizada$Params } from '../fn/notificacoes';
import { marcarTodasComoVisualizadas } from '../fn/notificacoes';
import { Page } from '../models/page';


/**
 * Notificações do usuário
 */
@Injectable({ providedIn: 'root' })
export class NotificacoesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listarNotificacoes()` */
  static readonly ListarNotificacoesPath = '/notificacoes';

  /**
   * Listar notificações.
   *
   * Notificações do usuário autenticado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarNotificacoes()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarNotificacoes$Response(params: ListarNotificacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarNotificacoes(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar notificações.
   *
   * Notificações do usuário autenticado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarNotificacoes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarNotificacoes(params: ListarNotificacoes$Params, context?: HttpContext): Observable<Page> {
    return this.listarNotificacoes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `contarNaoLidas()` */
  static readonly ContarNaoLidasPath = '/notificacoes/contagem';

  /**
   * Contar não lidas.
   *
   * Badge de notificações
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contarNaoLidas()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarNaoLidas$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return contarNaoLidas(this.http, this.rootUrl, context);
  }

  /**
   * Contar não lidas.
   *
   * Badge de notificações
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contarNaoLidas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarNaoLidas(context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.contarNaoLidas$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `marcarComoVisualizada()` */
  static readonly MarcarComoVisualizadaPath = '/notificacoes/{id}/visualizar';

  /**
   * Marcar como visualizada.
   *
   * Marca uma notificação como lida
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `marcarComoVisualizada()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoVisualizada$Response(params: MarcarComoVisualizada$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return marcarComoVisualizada(this.http, this.rootUrl, params, context);
  }

  /**
   * Marcar como visualizada.
   *
   * Marca uma notificação como lida
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `marcarComoVisualizada$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoVisualizada(params: MarcarComoVisualizada$Params, context?: HttpContext): Observable<void> {
    return this.marcarComoVisualizada$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `marcarTodasComoVisualizadas()` */
  static readonly MarcarTodasComoVisualizadasPath = '/notificacoes/visualizar-todas';

  /**
   * Marcar todas como visualizadas.
   *
   * Marca todas como lidas
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `marcarTodasComoVisualizadas()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarTodasComoVisualizadas$Response(context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return marcarTodasComoVisualizadas(this.http, this.rootUrl, context);
  }

  /**
   * Marcar todas como visualizadas.
   *
   * Marca todas como lidas
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `marcarTodasComoVisualizadas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarTodasComoVisualizadas(context?: HttpContext): Observable<void> {
    return this.marcarTodasComoVisualizadas$Response(context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deletarNotificacao()` */
  static readonly DeletarNotificacaoPath = '/notificacoes/{id}';

  /**
   * Excluir notificação.
   *
   * Remove uma notificação
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletarNotificacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletarNotificacao$Response(params: DeletarNotificacao$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletarNotificacao(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir notificação.
   *
   * Remove uma notificação
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletarNotificacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletarNotificacao(params: DeletarNotificacao$Params, context?: HttpContext): Observable<void> {
    return this.deletarNotificacao$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
