/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { arquivarPost } from '../fn/posts/arquivar-post';
import { ArquivarPost$Params } from '../fn/posts/arquivar-post';
import { atualizarPost } from '../fn/posts/atualizar-post';
import { AtualizarPost$Params } from '../fn/posts/atualizar-post';
import { buscarPorId } from '../fn/posts/buscar-por-id';
import { BuscarPorId$Params } from '../fn/posts/buscar-por-id';
import { criarPost } from '../fn/posts/criar-post';
import { CriarPost$Params } from '../fn/posts/criar-post';
import { curtirPost } from '../fn/posts/curtir-post';
import { CurtirPost$Params } from '../fn/posts/curtir-post';
import { desarquivarPost } from '../fn/posts/desarquivar-post';
import { DesarquivarPost$Params } from '../fn/posts/desarquivar-post';
import { descurtirPost } from '../fn/posts/descurtir-post';
import { DescurtirPost$Params } from '../fn/posts/descurtir-post';
import { excluirPost } from '../fn/posts/excluir-post';
import { ExcluirPost$Params } from '../fn/posts/excluir-post';
import { listarFeed } from '../fn/posts/listar-feed';
import { ListarFeed$Params } from '../fn/posts/listar-feed';
import { listarPostsDoUsuario } from '../fn/posts/listar-posts-do-usuario';
import { ListarPostsDoUsuario$Params } from '../fn/posts/listar-posts-do-usuario';
import { listarPostsPopulares } from '../fn/posts/listar-posts-populares';
import { ListarPostsPopulares$Params } from '../fn/posts/listar-posts-populares';
import { listarPostsPorHashtag } from '../fn/posts/listar-posts-por-hashtag';
import { ListarPostsPorHashtag$Params } from '../fn/posts/listar-posts-por-hashtag';
import { listarPostsPorLocalizacao } from '../fn/posts/listar-posts-por-localizacao';
import { ListarPostsPorLocalizacao$Params } from '../fn/posts/listar-posts-por-localizacao';
import { listarPostsSalvos } from '../fn/posts/listar-posts-salvos';
import { ListarPostsSalvos$Params } from '../fn/posts/listar-posts-salvos';
import { listarPostsSalvosPorColecao } from '../fn/posts/listar-posts-salvos-por-colecao';
import { ListarPostsSalvosPorColecao$Params } from '../fn/posts/listar-posts-salvos-por-colecao';
import { Page } from '../models/page';
import { PostResponseDto } from '../models/post-response-dto';
import { removerPostSalvo } from '../fn/posts/remover-post-salvo';
import { RemoverPostSalvo$Params } from '../fn/posts/remover-post-salvo';
import { salvarPost } from '../fn/posts/salvar-post';
import { SalvarPost$Params } from '../fn/posts/salvar-post';


/**
 * API para gerenciamento de posts
 */
@Injectable({ providedIn: 'root' })
export class PostsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `buscarPorId()` */
  static readonly BuscarPorIdPath = '/posts/{id}';

  /**
   * Buscar post por ID.
   *
   * Retorna os detalhes de um post específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarPorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarPorId$Response(params: BuscarPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
    return buscarPorId(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar post por ID.
   *
   * Retorna os detalhes de um post específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarPorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarPorId(params: BuscarPorId$Params, context?: HttpContext): Observable<PostResponseDto> {
    return this.buscarPorId$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponseDto>): PostResponseDto => r.body)
    );
  }

  /** Path part for operation `atualizarPost()` */
  static readonly AtualizarPostPath = '/posts/{id}';

  /**
   * Atualizar post.
   *
   * Atualiza um post existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarPost$Response(params: AtualizarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
    return atualizarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Atualizar post.
   *
   * Atualiza um post existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarPost(params: AtualizarPost$Params, context?: HttpContext): Observable<PostResponseDto> {
    return this.atualizarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponseDto>): PostResponseDto => r.body)
    );
  }

  /** Path part for operation `excluirPost()` */
  static readonly ExcluirPostPath = '/posts/{id}';

  /**
   * Excluir post.
   *
   * Remove permanentemente um post
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirPost$Response(params: ExcluirPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir post.
   *
   * Remove permanentemente um post
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirPost(params: ExcluirPost$Params, context?: HttpContext): Observable<void> {
    return this.excluirPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `criarPost()` */
  static readonly CriarPostPath = '/posts';

  /**
   * Criar novo post.
   *
   * Cria um novo post com opção de upload de arquivos
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `criarPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarPost$Response(params?: CriarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
    return criarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Criar novo post.
   *
   * Cria um novo post com opção de upload de arquivos
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `criarPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  criarPost(params?: CriarPost$Params, context?: HttpContext): Observable<PostResponseDto> {
    return this.criarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponseDto>): PostResponseDto => r.body)
    );
  }

  /** Path part for operation `salvarPost()` */
  static readonly SalvarPostPath = '/posts/{id}/salvar';

  /**
   * Salvar post.
   *
   * Salva um post, opcionalmente em uma coleção específica
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `salvarPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  salvarPost$Response(params: SalvarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return salvarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Salvar post.
   *
   * Salva um post, opcionalmente em uma coleção específica
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `salvarPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  salvarPost(params: SalvarPost$Params, context?: HttpContext): Observable<void> {
    return this.salvarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `curtirPost()` */
  static readonly CurtirPostPath = '/posts/{id}/curtir';

  /**
   * Curtir post.
   *
   * Adiciona uma curtida ao post
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `curtirPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  curtirPost$Response(params: CurtirPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
    return curtirPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Curtir post.
   *
   * Adiciona uma curtida ao post
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `curtirPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  curtirPost(params: CurtirPost$Params, context?: HttpContext): Observable<PostResponseDto> {
    return this.curtirPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponseDto>): PostResponseDto => r.body)
    );
  }

  /** Path part for operation `desarquivarPost()` */
  static readonly DesarquivarPostPath = '/posts/{id}/desarquivar';

  /**
   * Desarquivar post.
   *
   * Desarquiva um post anteriormente arquivado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `desarquivarPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  desarquivarPost$Response(params: DesarquivarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return desarquivarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Desarquivar post.
   *
   * Desarquiva um post anteriormente arquivado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `desarquivarPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  desarquivarPost(params: DesarquivarPost$Params, context?: HttpContext): Observable<void> {
    return this.desarquivarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `arquivarPost()` */
  static readonly ArquivarPostPath = '/posts/{id}/arquivar';

  /**
   * Arquivar post.
   *
   * Arquiva um post sem removê-lo
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `arquivarPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  arquivarPost$Response(params: ArquivarPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return arquivarPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Arquivar post.
   *
   * Arquiva um post sem removê-lo
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `arquivarPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  arquivarPost(params: ArquivarPost$Params, context?: HttpContext): Observable<void> {
    return this.arquivarPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listarPostsDoUsuario()` */
  static readonly ListarPostsDoUsuarioPath = '/posts/usuario/{usuarioId}';

  /**
   * Listar posts de um usuário.
   *
   * Retorna os posts publicados por um usuário específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsDoUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsDoUsuario$Response(params: ListarPostsDoUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsDoUsuario(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts de um usuário.
   *
   * Retorna os posts publicados por um usuário específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsDoUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsDoUsuario(params: ListarPostsDoUsuario$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsDoUsuario$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarPostsSalvos()` */
  static readonly ListarPostsSalvosPath = '/posts/salvos';

  /**
   * Listar posts salvos.
   *
   * Retorna os posts salvos pelo usuário logado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsSalvos()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsSalvos$Response(params: ListarPostsSalvos$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsSalvos(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts salvos.
   *
   * Retorna os posts salvos pelo usuário logado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsSalvos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsSalvos(params: ListarPostsSalvos$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsSalvos$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarPostsSalvosPorColecao()` */
  static readonly ListarPostsSalvosPorColecaoPath = '/posts/salvos/colecao/{colecao}';

  /**
   * Listar posts salvos por coleção.
   *
   * Retorna posts salvos pelo usuário em uma coleção específica
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsSalvosPorColecao()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsSalvosPorColecao$Response(params: ListarPostsSalvosPorColecao$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsSalvosPorColecao(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts salvos por coleção.
   *
   * Retorna posts salvos pelo usuário em uma coleção específica
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsSalvosPorColecao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsSalvosPorColecao(params: ListarPostsSalvosPorColecao$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsSalvosPorColecao$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarPostsPopulares()` */
  static readonly ListarPostsPopularesPath = '/posts/populares';

  /**
   * Listar posts populares.
   *
   * Retorna os posts mais populares da plataforma
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsPopulares()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPopulares$Response(params: ListarPostsPopulares$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsPopulares(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts populares.
   *
   * Retorna os posts mais populares da plataforma
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsPopulares$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPopulares(params: ListarPostsPopulares$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsPopulares$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarPostsPorLocalizacao()` */
  static readonly ListarPostsPorLocalizacaoPath = '/posts/localizacao';

  /**
   * Listar posts por localização.
   *
   * Retorna posts associados a uma localização específica
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsPorLocalizacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPorLocalizacao$Response(params: ListarPostsPorLocalizacao$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsPorLocalizacao(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts por localização.
   *
   * Retorna posts associados a uma localização específica
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsPorLocalizacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPorLocalizacao(params: ListarPostsPorLocalizacao$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsPorLocalizacao$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarPostsPorHashtag()` */
  static readonly ListarPostsPorHashtagPath = '/posts/hashtag/{nome}';

  /**
   * Listar posts por hashtag.
   *
   * Retorna posts que contêm uma hashtag específica
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarPostsPorHashtag()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPorHashtag$Response(params: ListarPostsPorHashtag$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarPostsPorHashtag(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar posts por hashtag.
   *
   * Retorna posts que contêm uma hashtag específica
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarPostsPorHashtag$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarPostsPorHashtag(params: ListarPostsPorHashtag$Params, context?: HttpContext): Observable<Page> {
    return this.listarPostsPorHashtag$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarFeed()` */
  static readonly ListarFeedPath = '/posts/feed';

  /**
   * Listar feed do usuário.
   *
   * Retorna o feed personalizado do usuário logado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarFeed()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarFeed$Response(params: ListarFeed$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarFeed(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar feed do usuário.
   *
   * Retorna o feed personalizado do usuário logado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarFeed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarFeed(params: ListarFeed$Params, context?: HttpContext): Observable<Page> {
    return this.listarFeed$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `removerPostSalvo()` */
  static readonly RemoverPostSalvoPath = '/posts/{id}/remover-salvo';

  /**
   * Remover post salvo.
   *
   * Remove um post da lista de salvos do usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removerPostSalvo()` instead.
   *
   * This method doesn't expect any request body.
   */
  removerPostSalvo$Response(params: RemoverPostSalvo$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return removerPostSalvo(this.http, this.rootUrl, params, context);
  }

  /**
   * Remover post salvo.
   *
   * Remove um post da lista de salvos do usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removerPostSalvo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removerPostSalvo(params: RemoverPostSalvo$Params, context?: HttpContext): Observable<void> {
    return this.removerPostSalvo$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `descurtirPost()` */
  static readonly DescurtirPostPath = '/posts/{id}/descurtir';

  /**
   * Remover curtida.
   *
   * Remove a curtida do usuário em um post
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `descurtirPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  descurtirPost$Response(params: DescurtirPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponseDto>> {
    return descurtirPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Remover curtida.
   *
   * Remove a curtida do usuário em um post
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `descurtirPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  descurtirPost(params: DescurtirPost$Params, context?: HttpContext): Observable<PostResponseDto> {
    return this.descurtirPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponseDto>): PostResponseDto => r.body)
    );
  }

}
