/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom, Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { chavePublica } from '../fn/push';
import { desinscreverPush, DesinscreverPush$Params } from '../fn/push';
import { inscreverPush, InscreverPush$Params } from '../fn/push';


/**
 * Web Push (VAPID)
 */
@Injectable({ providedIn: 'root' })
export class PushService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `chavePublica()` */
  static readonly ChavePublicaPath = '/push/vapid-public-key';

  /**
   * Chave pública VAPID.
   *
   * Para assinar no navegador
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `chavePublica()` instead.
   *
   * This method doesn't expect any request body.
   */
  chavePublica$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return chavePublica(this.http, this.rootUrl, context);
  }

  /**
   * Chave pública VAPID.
   *
   * Para assinar no navegador
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `chavePublica$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  chavePublica(context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.chavePublica$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

  /** Path part for operation `inscreverPush()` */
  static readonly InscreverPushPath = '/push/subscriptions';

  /**
   * Inscrever dispositivo.
   *
   * Idempotente por endpoint
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `inscreverPush()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inscreverPush$Response(params: InscreverPush$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return inscreverPush(this.http, this.rootUrl, params, context);
  }

  /**
   * Inscrever dispositivo.
   *
   * Idempotente por endpoint
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `inscreverPush$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  inscreverPush(params: InscreverPush$Params, context?: HttpContext): Observable<void> {
    return this.inscreverPush$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `desinscreverPush()` */
  static readonly DesinscreverPushPath = '/push/subscriptions';

  /**
   * Desinscrever dispositivo.
   *
   * Remove pelo endpoint
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `desinscreverPush()` instead.
   *
   * This method doesn't expect any request body.
   */
  desinscreverPush$Response(params: DesinscreverPush$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return desinscreverPush(this.http, this.rootUrl, params, context);
  }

  /**
   * Desinscrever dispositivo.
   *
   * Remove pelo endpoint
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `desinscreverPush$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  desinscreverPush(params: DesinscreverPush$Params, context?: HttpContext): Observable<void> {
    return this.desinscreverPush$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /**
   * Ativa push neste navegador: assina no PushManager e registra no back.
   * Exige HTTPS (ou localhost) + Service Worker.
   */
  async ativarNesteDispositivo(): Promise<void> {
    if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
      throw new Error('Push não suportado neste navegador');
    }
    const chaves = await firstValueFrom(this.chavePublica());
    const publicKey = chaves?.['publicKey'];
    if (!publicKey) {
      throw new Error('Chave VAPID indisponível');
    }
    const registro = await navigator.serviceWorker.ready;
    const inscricao = await registro.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: this.base64ParaBytes(publicKey),
    });
    const p256dh = inscricao.getKey('p256dh');
    const auth = inscricao.getKey('auth');
    if (!p256dh || !auth) {
      throw new Error('Chaves da inscrição indisponíveis');
    }
    await firstValueFrom(
      this.inscreverPush({
        body: {
          endpoint: inscricao.endpoint,
          p256dh: this.bytesParaBase64(p256dh),
          auth: this.bytesParaBase64(auth),
        },
      })
    );
  }

  private base64ParaBytes(base64url: string): Uint8Array {
    const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
    const binaria = window.atob(base64);
    const bytes = new Uint8Array(binaria.length);
    for (let i = 0; i < binaria.length; i++) {
      bytes[i] = binaria.charCodeAt(i);
    }
    return bytes;
  }

  private bytesParaBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    let binaria = '';
    for (let i = 0; i < bytes.length; i++) {
      binaria += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binaria).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  }
}
