/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { alterarNotificacoes } from '../fn/seguidores/alterar-notificacoes';
import { AlterarNotificacoes$Params } from '../fn/seguidores/alterar-notificacoes';
import { aceitarSolicitacao } from '../fn/seguidores/aceitar-solicitacao';
import { AceitarSolicitacao$Params } from '../fn/seguidores/aceitar-solicitacao';
import { buscarSeguidosAleatorios } from '../fn/seguidores/buscar-seguidos-aleatorios';
import { BuscarSeguidosAleatorios$Params } from '../fn/seguidores/buscar-seguidos-aleatorios';
import { contarSolicitacoes } from '../fn/seguidores/contar-solicitacoes';
import { contarSeguidoresESeguidos } from '../fn/seguidores/contar-seguidores-e-seguidos';
import { ContarSeguidoresESeguidos$Params } from '../fn/seguidores/contar-seguidores-e-seguidos';
import { deixarDeSeguir } from '../fn/seguidores/deixar-de-seguir';
import { DeixarDeSeguir$Params } from '../fn/seguidores/deixar-de-seguir';
import { listarSolicitacoes } from '../fn/seguidores/listar-solicitacoes';
import { ListarSolicitacoes$Params } from '../fn/seguidores/listar-solicitacoes';
import { listarSeguidores1 } from '../fn/seguidores/listar-seguidores-1';
import { ListarSeguidores1$Params } from '../fn/seguidores/listar-seguidores-1';
import { listarSeguidos1 } from '../fn/seguidores/listar-seguidos-1';
import { ListarSeguidos1$Params } from '../fn/seguidores/listar-seguidos-1';
import { rejeitarSolicitacao } from '../fn/seguidores/rejeitar-solicitacao';
import { RejeitarSolicitacao$Params } from '../fn/seguidores/rejeitar-solicitacao';
import { ContagemSeguidoresDto } from '../models/contagem-seguidores-dto';
import { Page } from '../models/page';
import { SeguidorResponseDto } from '../models/seguidor-response-dto';
import { seguirUsuario } from '../fn/seguidores/seguir-usuario';
import { SeguirUsuario$Params } from '../fn/seguidores/seguir-usuario';
import { UsuarioSummaryDto } from '../models/usuario-summary-dto';
import { verificarSeguimento } from '../fn/seguidores/verificar-seguimento';
import { VerificarSeguimento$Params } from '../fn/seguidores/verificar-seguimento';
import { VerificarSeguimentoDto } from '../models/verificar-seguimento-dto';


/**
 * API para gerenciamento de seguidores
 */
@Injectable({ providedIn: 'root' })
export class SeguidoresService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `seguirUsuario()` */
  static readonly SeguirUsuarioPath = '/api/seguidores/{usuarioId}/seguir';

  /**
   * Seguir usuário.
   *
   * Começa a seguir um usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `seguirUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  seguirUsuario$Response(params: SeguirUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<SeguidorResponseDto>> {
    return seguirUsuario(this.http, this.rootUrl, params, context);
  }

  /**
   * Seguir usuário.
   *
   * Começa a seguir um usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `seguirUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  seguirUsuario(params: SeguirUsuario$Params, context?: HttpContext): Observable<SeguidorResponseDto> {
    return this.seguirUsuario$Response(params, context).pipe(
      map((r: StrictHttpResponse<SeguidorResponseDto>): SeguidorResponseDto => r.body)
    );
  }

  /** Path part for operation `alterarNotificacoes()` */
  static readonly AlterarNotificacoesPath = '/api/seguidores/{usuarioId}/notificacoes';

  /**
   * Alterar notificações.
   *
   * Ativa ou desativa notificações de um seguido
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `alterarNotificacoes()` instead.
   *
   * This method doesn't expect any request body.
   */
  alterarNotificacoes$Response(params: AlterarNotificacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return alterarNotificacoes(this.http, this.rootUrl, params, context);
  }

  /**
   * Alterar notificações.
   *
   * Ativa ou desativa notificações de um seguido
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `alterarNotificacoes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  alterarNotificacoes(params: AlterarNotificacoes$Params, context?: HttpContext): Observable<void> {
    return this.alterarNotificacoes$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `verificarSeguimento()` */
  static readonly VerificarSeguimentoPath = '/api/seguidores/seguindo/{usuarioId}';

  /**
   * Verificar seguimento.
   *
   * Verifica se um usuário está seguindo outro
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `verificarSeguimento()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificarSeguimento$Response(params: VerificarSeguimento$Params, context?: HttpContext): Observable<StrictHttpResponse<VerificarSeguimentoDto>> {
    return verificarSeguimento(this.http, this.rootUrl, params, context);
  }

  /**
   * Verificar seguimento.
   *
   * Verifica se um usuário está seguindo outro
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `verificarSeguimento$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  verificarSeguimento(params: VerificarSeguimento$Params, context?: HttpContext): Observable<VerificarSeguimentoDto> {
    return this.verificarSeguimento$Response(params, context).pipe(
      map((r: StrictHttpResponse<VerificarSeguimentoDto>): VerificarSeguimentoDto => r.body)
    );
  }

  /** Path part for operation `listarSeguidos1()` */
  static readonly ListarSeguidos1Path = '/api/seguidores/seguidos/{usuarioId}';

  /**
   * Listar seguidos.
   *
   * Retorna a lista de usuários que um usuário segue
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSeguidos1()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidos1$Response(params: ListarSeguidos1$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSeguidos1(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar seguidos.
   *
   * Retorna a lista de usuários que um usuário segue
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSeguidos1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidos1(params: ListarSeguidos1$Params, context?: HttpContext): Observable<Page> {
    return this.listarSeguidos1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarSeguidores1()` */
  static readonly ListarSeguidores1Path = '/api/seguidores/seguidores/{usuarioId}';

  /**
   * Listar seguidores.
   *
   * Retorna a lista de seguidores de um usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSeguidores1()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidores1$Response(params: ListarSeguidores1$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSeguidores1(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar seguidores.
   *
   * Retorna a lista de seguidores de um usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSeguidores1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidores1(params: ListarSeguidores1$Params, context?: HttpContext): Observable<Page> {
    return this.listarSeguidores1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `contarSeguidoresESeguidos()` */
  static readonly ContarSeguidoresESeguidosPath = '/api/seguidores/contagem/{usuarioId}';

  /**
   * Contagem de seguidores e seguidos.
   *
   * Retorna a quantidade de seguidores e seguidos de um usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contarSeguidoresESeguidos()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarSeguidoresESeguidos$Response(params: ContarSeguidoresESeguidos$Params, context?: HttpContext): Observable<StrictHttpResponse<ContagemSeguidoresDto>> {
    return contarSeguidoresESeguidos(this.http, this.rootUrl, params, context);
  }

  /**
   * Contagem de seguidores e seguidos.
   *
   * Retorna a quantidade de seguidores e seguidos de um usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contarSeguidoresESeguidos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarSeguidoresESeguidos(params: ContarSeguidoresESeguidos$Params, context?: HttpContext): Observable<ContagemSeguidoresDto> {
    return this.contarSeguidoresESeguidos$Response(params, context).pipe(
      map((r: StrictHttpResponse<ContagemSeguidoresDto>): ContagemSeguidoresDto => r.body)
    );
  }

  /** Path part for operation `buscarSeguidosAleatorios()` */
  static readonly BuscarSeguidosAleatoriosPath = '/api/seguidores/aleatorios';

  /**
   * Buscar seguidos aleatórios.
   *
   * Retorna uma lista aleatória de usuários seguidos
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarSeguidosAleatorios()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarSeguidosAleatorios$Response(params?: BuscarSeguidosAleatorios$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UsuarioSummaryDto>>> {
    return buscarSeguidosAleatorios(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar seguidos aleatórios.
   *
   * Retorna uma lista aleatória de usuários seguidos
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarSeguidosAleatorios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarSeguidosAleatorios(params?: BuscarSeguidosAleatorios$Params, context?: HttpContext): Observable<Array<UsuarioSummaryDto>> {
    return this.buscarSeguidosAleatorios$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UsuarioSummaryDto>>): Array<UsuarioSummaryDto> => r.body)
    );
  }

  /** Path part for operation `deixarDeSeguir()` */
  static readonly DeixarDeSeguirPath = '/api/seguidores/{usuarioId}/deixar-de-seguir';

  /**
   * Deixar de seguir.
   *
   * Deixa de seguir um usuário
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deixarDeSeguir()` instead.
   *
   * This method doesn't expect any request body.
   */
  deixarDeSeguir$Response(params: DeixarDeSeguir$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deixarDeSeguir(this.http, this.rootUrl, params, context);
  }

  /**
   * Deixar de seguir.
   *
   * Deixa de seguir um usuário
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deixarDeSeguir$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deixarDeSeguir(params: DeixarDeSeguir$Params, context?: HttpContext): Observable<void> {
    return this.deixarDeSeguir$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listarSolicitacoes()` */
  static readonly ListarSolicitacoesPath = '/seguidores/solicitacoes';

  /**
   * Listar solicitações de seguimento.
   *
   * Solicitações pendentes para contas privadas
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSolicitacoes()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSolicitacoes$Response(params: ListarSolicitacoes$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSolicitacoes(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar solicitações de seguimento.
   *
   * Solicitações pendentes para contas privadas
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSolicitacoes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSolicitacoes(params: ListarSolicitacoes$Params, context?: HttpContext): Observable<Page> {
    return this.listarSolicitacoes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `contarSolicitacoes()` */
  static readonly ContarSolicitacoesPath = '/seguidores/solicitacoes/contagem';

  /**
   * Contar solicitações pendentes.
   *
   * Badge de solicitações de seguimento
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contarSolicitacoes()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarSolicitacoes$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return contarSolicitacoes(this.http, this.rootUrl, context);
  }

  /**
   * Contar solicitações pendentes.
   *
   * Badge de solicitações de seguimento
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contarSolicitacoes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contarSolicitacoes(context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.contarSolicitacoes$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `aceitarSolicitacao()` */
  static readonly AceitarSolicitacaoPath = '/seguidores/solicitacoes/{id}/aceitar';

  /**
   * Aceitar solicitação.
   *
   * Aceita uma solicitação de seguimento pendente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `aceitarSolicitacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  aceitarSolicitacao$Response(params: AceitarSolicitacao$Params, context?: HttpContext): Observable<StrictHttpResponse<SeguidorResponseDto>> {
    return aceitarSolicitacao(this.http, this.rootUrl, params, context);
  }

  /**
   * Aceitar solicitação.
   *
   * Aceita uma solicitação de seguimento pendente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `aceitarSolicitacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  aceitarSolicitacao(params: AceitarSolicitacao$Params, context?: HttpContext): Observable<SeguidorResponseDto> {
    return this.aceitarSolicitacao$Response(params, context).pipe(
      map((r: StrictHttpResponse<SeguidorResponseDto>): SeguidorResponseDto => r.body)
    );
  }

  /** Path part for operation `rejeitarSolicitacao()` */
  static readonly RejeitarSolicitacaoPath = '/seguidores/solicitacoes/{id}';

  /**
   * Rejeitar solicitação.
   *
   * Rejeita uma solicitação de seguimento pendente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rejeitarSolicitacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejeitarSolicitacao$Response(params: RejeitarSolicitacao$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return rejeitarSolicitacao(this.http, this.rootUrl, params, context);
  }

  /**
   * Rejeitar solicitação.
   *
   * Rejeita uma solicitação de seguimento pendente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rejeitarSolicitacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  rejeitarSolicitacao(params: RejeitarSolicitacao$Params, context?: HttpContext): Observable<void> {
    return this.rejeitarSolicitacao$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
