/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { definirNota, DefinirNota$Params } from '../fn/status';
import { listarNotas } from '../fn/status';
import { statusPorUsuario, StatusPorUsuario$Params } from '../fn/status';
import { StatusNotaDto } from '../models/status-nota-dto';
import { StatusUsuarioResponseDto } from '../models/status-usuario-response-dto';


/**
 * Notas e presença
 */
@Injectable({ providedIn: 'root' })
export class StatusService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listarNotas()` */
  static readonly ListarNotasPath = '/status/notas';

  /**
   * Notas de seguidos.
   *
   * Notas (24h) de seguidos aceitos + própria
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarNotas()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarNotas$Response(context?: HttpContext): Observable<StrictHttpResponse<Array<StatusNotaDto>>> {
    return listarNotas(this.http, this.rootUrl, context);
  }

  /**
   * Notas de seguidos.
   *
   * Notas (24h) de seguidos aceitos + própria
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarNotas$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarNotas(context?: HttpContext): Observable<Array<StatusNotaDto>> {
    return this.listarNotas$Response(context).pipe(
      map((r: StrictHttpResponse<Array<StatusNotaDto>>): Array<StatusNotaDto> => r.body)
    );
  }

  /** Path part for operation `definirNota()` */
  static readonly DefinirNotaPath = '/status/nota';

  /**
   * Definir nota.
   *
   * Nota curta (máx. 60 caracteres); vazia apaga
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `definirNota()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  definirNota$Response(params: DefinirNota$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusNotaDto>> {
    return definirNota(this.http, this.rootUrl, params, context);
  }

  /**
   * Definir nota.
   *
   * Nota curta (máx. 60 caracteres); vazia apaga
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `definirNota$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  definirNota(params: DefinirNota$Params, context?: HttpContext): Observable<StatusNotaDto> {
    return this.definirNota$Response(params, context).pipe(
      map((r: StrictHttpResponse<StatusNotaDto>): StatusNotaDto => r.body)
    );
  }

  /** Path part for operation `statusPorUsuario()` */
  static readonly StatusPorUsuarioPath = '/status/{usuarioId}';

  /**
   * Status de um usuário.
   *
   * Online e último acesso
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `statusPorUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  statusPorUsuario$Response(params: StatusPorUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusUsuarioResponseDto>> {
    return statusPorUsuario(this.http, this.rootUrl, params, context);
  }

  /**
   * Status de um usuário.
   *
   * Online e último acesso
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `statusPorUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  statusPorUsuario(params: StatusPorUsuario$Params, context?: HttpContext): Observable<StatusUsuarioResponseDto> {
    return this.statusPorUsuario$Response(params, context).pipe(
      map((r: StrictHttpResponse<StatusUsuarioResponseDto>): StatusUsuarioResponseDto => r.body)
    );
  }

}
