/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adicionarImagemStorie } from '../fn/stories/adicionar-imagem-storie';
import { AdicionarImagemStorie$Params } from '../fn/stories/adicionar-imagem-storie';
import { buscarStoriePorId } from '../fn/stories/buscar-storie-por-id';
import { BuscarStoriePorId$Params } from '../fn/stories/buscar-storie-por-id';
import { criarStorie } from '../fn/stories/criar-storie';
import { CriarStorie$Params } from '../fn/stories/criar-storie';
import { destacarStorie } from '../fn/stories/destacar-storie';
import { DestacarStorie$Params } from '../fn/stories/destacar-storie';
import { excluirStorie } from '../fn/stories/excluir-storie';
import { ExcluirStorie$Params } from '../fn/stories/excluir-storie';
import { listarStoriesDestacados } from '../fn/stories/listar-stories-destacados';
import { ListarStoriesDestacados$Params } from '../fn/stories/listar-stories-destacados';
import { listarStoriesDoFeed } from '../fn/stories/listar-stories-do-feed';
import { ListarStoriesDoFeed$Params } from '../fn/stories/listar-stories-do-feed';
import { listarStoriesDoUsuario } from '../fn/stories/listar-stories-do-usuario';
import { ListarStoriesDoUsuario$Params } from '../fn/stories/listar-stories-do-usuario';
import { marcarComoVisualizado } from '../fn/stories/marcar-como-visualizado';
import { MarcarComoVisualizado$Params } from '../fn/stories/marcar-como-visualizado';
import { StorieResponseDto } from '../models/storie-response-dto';


/**
 * Operações relacionadas a stories temporários
 */
@Injectable({ providedIn: 'root' })
export class StoriesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `criarStorie()` */
  static readonly CriarStoriePath = '/stories';

  /**
   * Criar um novo storie.
   *
   * Cria um novo storie com duração de 24 horas
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `criarStorie()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  criarStorie$Response(params?: CriarStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
    return criarStorie(this.http, this.rootUrl, params, context);
  }

  /**
   * Criar um novo storie.
   *
   * Cria um novo storie com duração de 24 horas
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `criarStorie$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  criarStorie(params?: CriarStorie$Params, context?: HttpContext): Observable<StorieResponseDto> {
    return this.criarStorie$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorieResponseDto>): StorieResponseDto => r.body)
    );
  }

  /** Path part for operation `marcarComoVisualizado()` */
  static readonly MarcarComoVisualizadoPath = '/stories/{id}/visualizar';

  /**
   * Marcar storie como visualizado.
   *
   * Registra que o usuário autenticado visualizou o storie
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `marcarComoVisualizado()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoVisualizado$Response(params: MarcarComoVisualizado$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
    return marcarComoVisualizado(this.http, this.rootUrl, params, context);
  }

  /**
   * Marcar storie como visualizado.
   *
   * Registra que o usuário autenticado visualizou o storie
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `marcarComoVisualizado$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  marcarComoVisualizado(params: MarcarComoVisualizado$Params, context?: HttpContext): Observable<StorieResponseDto> {
    return this.marcarComoVisualizado$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorieResponseDto>): StorieResponseDto => r.body)
    );
  }

  /** Path part for operation `adicionarImagemStorie()` */
  static readonly AdicionarImagemStoriePath = '/stories/{id}/imagem';

  /**
   * Adicionar imagem ao storie.
   *
   * Adiciona ou atualiza a imagem de um storie
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adicionarImagemStorie()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adicionarImagemStorie$Response(params: AdicionarImagemStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
    return adicionarImagemStorie(this.http, this.rootUrl, params, context);
  }

  /**
   * Adicionar imagem ao storie.
   *
   * Adiciona ou atualiza a imagem de um storie
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adicionarImagemStorie$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adicionarImagemStorie(params: AdicionarImagemStorie$Params, context?: HttpContext): Observable<StorieResponseDto> {
    return this.adicionarImagemStorie$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorieResponseDto>): StorieResponseDto => r.body)
    );
  }

  /** Path part for operation `destacarStorie()` */
  static readonly DestacarStoriePath = '/stories/{id}/destacar/{destaqueId}';

  /**
   * Destacar storie.
   *
   * Adiciona o storie a um destaque específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `destacarStorie()` instead.
   *
   * This method doesn't expect any request body.
   */
  destacarStorie$Response(params: DestacarStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
    return destacarStorie(this.http, this.rootUrl, params, context);
  }

  /**
   * Destacar storie.
   *
   * Adiciona o storie a um destaque específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `destacarStorie$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  destacarStorie(params: DestacarStorie$Params, context?: HttpContext): Observable<StorieResponseDto> {
    return this.destacarStorie$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorieResponseDto>): StorieResponseDto => r.body)
    );
  }

  /** Path part for operation `buscarStoriePorId()` */
  static readonly BuscarStoriePorIdPath = '/stories/{id}';

  /**
   * Buscar storie por ID.
   *
   * Busca um storie específico pelo seu ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarStoriePorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarStoriePorId$Response(params: BuscarStoriePorId$Params, context?: HttpContext): Observable<StrictHttpResponse<StorieResponseDto>> {
    return buscarStoriePorId(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar storie por ID.
   *
   * Busca um storie específico pelo seu ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarStoriePorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarStoriePorId(params: BuscarStoriePorId$Params, context?: HttpContext): Observable<StorieResponseDto> {
    return this.buscarStoriePorId$Response(params, context).pipe(
      map((r: StrictHttpResponse<StorieResponseDto>): StorieResponseDto => r.body)
    );
  }

  /** Path part for operation `excluirStorie()` */
  static readonly ExcluirStoriePath = '/stories/{id}';

  /**
   * Excluir storie.
   *
   * Remove um storie existente
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirStorie()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirStorie$Response(params: ExcluirStorie$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirStorie(this.http, this.rootUrl, params, context);
  }

  /**
   * Excluir storie.
   *
   * Remove um storie existente
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirStorie$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirStorie(params: ExcluirStorie$Params, context?: HttpContext): Observable<void> {
    return this.excluirStorie$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listarStoriesDoUsuario()` */
  static readonly ListarStoriesDoUsuarioPath = '/stories/usuario/{autorId}';

  /**
   * Listar stories de um usuário.
   *
   * Lista todos os stories ativos de um usuário específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarStoriesDoUsuario()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDoUsuario$Response(params: ListarStoriesDoUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorieResponseDto>>> {
    return listarStoriesDoUsuario(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar stories de um usuário.
   *
   * Lista todos os stories ativos de um usuário específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarStoriesDoUsuario$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDoUsuario(params: ListarStoriesDoUsuario$Params, context?: HttpContext): Observable<Array<StorieResponseDto>> {
    return this.listarStoriesDoUsuario$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StorieResponseDto>>): Array<StorieResponseDto> => r.body)
    );
  }

  /** Path part for operation `listarStoriesDoFeed()` */
  static readonly ListarStoriesDoFeedPath = '/stories/feed';

  /**
   * Listar stories do feed.
   *
   * Lista todos os stories ativos de usuários seguidos
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarStoriesDoFeed()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDoFeed$Response(params?: ListarStoriesDoFeed$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorieResponseDto>>> {
    return listarStoriesDoFeed(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar stories do feed.
   *
   * Lista todos os stories ativos de usuários seguidos
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarStoriesDoFeed$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDoFeed(params?: ListarStoriesDoFeed$Params, context?: HttpContext): Observable<Array<StorieResponseDto>> {
    return this.listarStoriesDoFeed$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StorieResponseDto>>): Array<StorieResponseDto> => r.body)
    );
  }

  /** Path part for operation `listarStoriesDestacados()` */
  static readonly ListarStoriesDestacadosPath = '/stories/destacados';

  /**
   * Listar stories destacados.
   *
   * Lista todos os stories destacados do usuário autenticado
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarStoriesDestacados()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDestacados$Response(params?: ListarStoriesDestacados$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StorieResponseDto>>> {
    return listarStoriesDestacados(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar stories destacados.
   *
   * Lista todos os stories destacados do usuário autenticado
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarStoriesDestacados$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarStoriesDestacados(params?: ListarStoriesDestacados$Params, context?: HttpContext): Observable<Array<StorieResponseDto>> {
    return this.listarStoriesDestacados$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StorieResponseDto>>): Array<StorieResponseDto> => r.body)
    );
  }

}
