/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { atualizarUsuario } from '../fn/usuarios/atualizar-usuario';
import { AtualizarUsuario$Params } from '../fn/usuarios/atualizar-usuario';
import { atualizarPrivado } from '../fn/usuarios/atualizar-privado';
import { AtualizarPrivado$Params } from '../fn/usuarios/atualizar-privado';
import { analytics } from '../fn/usuarios/criador';
import { atualizarChavePix, AtualizarChavePix$Params } from '../fn/usuarios/criador';
import { atualizarTipoConta, AtualizarTipoConta$Params } from '../fn/usuarios/criador';
import { buscarUsuarioPorId } from '../fn/usuarios/buscar-usuario-por-id';
import { excluirConta } from '../fn/usuarios/conta';
import { exportarDados } from '../fn/usuarios/conta';
import { solicitarVerificacao } from '../fn/usuarios/conta';
import { BuscarUsuarioPorId$Params } from '../fn/usuarios/buscar-usuario-por-id';
import { buscarUsuarioPorUsername } from '../fn/usuarios/buscar-usuario-por-username';
import { BuscarUsuarioPorUsername$Params } from '../fn/usuarios/buscar-usuario-por-username';
import { buscarUsuarios } from '../fn/usuarios/buscar-usuarios';
import { BuscarUsuarios$Params } from '../fn/usuarios/buscar-usuarios';
import { listarSeguidores } from '../fn/usuarios/listar-seguidores';
import { ListarSeguidores$Params } from '../fn/usuarios/listar-seguidores';
import { listarSeguidos } from '../fn/usuarios/listar-seguidos';
import { ListarSeguidos$Params } from '../fn/usuarios/listar-seguidos';
import { listarSugestoesUsuarios } from '../fn/usuarios/listar-sugestoes-usuarios';
import { ListarSugestoesUsuarios$Params } from '../fn/usuarios/listar-sugestoes-usuarios';
import { listarUsuariosMaisFamosos } from '../fn/usuarios/listar-usuarios-mais-famosos';
import { ListarUsuariosMaisFamosos$Params } from '../fn/usuarios/listar-usuarios-mais-famosos';
import { listarUsuariosPorAmigosEmComum } from '../fn/usuarios/listar-usuarios-por-amigos-em-comum';
import { ListarUsuariosPorAmigosEmComum$Params } from '../fn/usuarios/listar-usuarios-por-amigos-em-comum';
import { Page } from '../models/page';
import { AnalyticsDto } from '../models/analytics-dto';
import { UsuarioResponseDto } from '../models/usuario-response-dto';


/**
 * Gerenciamento de usuários
 */
@Injectable({ providedIn: 'root' })
export class UsuariosService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `buscarUsuarioPorId()` */
  static readonly BuscarUsuarioPorIdPath = '/usuarios/{id}';

  /**
   * Buscar usuário por ID.
   *
   * Retorna os detalhes de um usuário específico pelo ID
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarUsuarioPorId()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarioPorId$Response(params: BuscarUsuarioPorId$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return buscarUsuarioPorId(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar usuário por ID.
   *
   * Retorna os detalhes de um usuário específico pelo ID
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarUsuarioPorId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarioPorId(params: BuscarUsuarioPorId$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.buscarUsuarioPorId$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

  /** Path part for operation `atualizarUsuario()` */
  static readonly AtualizarUsuarioPath = '/usuarios/{id}';

  /**
   * Registrar usuário.
   *
   * Registra um novo usuário com foto de perfil
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registrar()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  atualizarUsuario$Response(params: AtualizarUsuario$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return atualizarUsuario(this.http, this.rootUrl, params, context);
  }

  /**
   * Registrar usuário.
   *
   * Registra um novo usuário com foto de perfil
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registrar$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  atualizarUsuario(params: AtualizarUsuario$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.atualizarUsuario$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

  /** Path part for operation `atualizarPrivado()` */
  static readonly AtualizarPrivadoPath = '/usuarios/{id}/privado';

  /**
   * Alternar conta privada.
   *
   * Ativa ou desativa a privacidade da conta
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarPrivado()` instead.
   *
   * This method doesn't expect any request body.
   */
  atualizarPrivado$Response(params: AtualizarPrivado$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return atualizarPrivado(this.http, this.rootUrl, params, context);
  }

  /**
   * Alternar conta privada.
   *
   * Ativa ou desativa a privacidade da conta
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarPrivado$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  atualizarPrivado(params: AtualizarPrivado$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.atualizarPrivado$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

  /** Path part for operation `solicitarVerificacao()` */
  static readonly SolicitarVerificacaoPath = '/usuarios/eu/solicitar-verificacao';

  /**
   * Solicitar selo de verificação.
   *
   * Entra na fila de moderação
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `solicitarVerificacao()` instead.
   *
   * This method doesn't expect any request body.
   */
  solicitarVerificacao$Response(context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return solicitarVerificacao(this.http, this.rootUrl, context);
  }

  /**
   * Solicitar selo de verificação.
   *
   * Entra na fila de moderação
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `solicitarVerificacao$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  solicitarVerificacao(context?: HttpContext): Observable<void> {
    return this.solicitarVerificacao$Response(context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `exportarDados()` */
  static readonly ExportarDadosPath = '/usuarios/eu/exportar';

  /**
   * Exportar meus dados (LGPD).
   *
   * JSON com perfil, contagens e posts
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `exportarDados()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportarDados$Response(context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: any;
}>> {
    return exportarDados(this.http, this.rootUrl, context);
  }

  /**
   * Exportar meus dados (LGPD).
   *
   * JSON com perfil, contagens e posts
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `exportarDados$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  exportarDados(context?: HttpContext): Observable<{
[key: string]: any;
}> {
    return this.exportarDados$Response(context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: any;
}>): {
[key: string]: any;
} => r.body)
    );
  }

  /** Path part for operation `excluirConta()` */
  static readonly ExcluirContaPath = '/usuarios/eu';

  /**
   * Excluir minha conta (LGPD).
   *
   * Anonimiza a conta; ação irreversível
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `excluirConta()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirConta$Response(context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return excluirConta(this.http, this.rootUrl, context);
  }

  /**
   * Excluir minha conta (LGPD).
   *
   * Anonimiza a conta; ação irreversível
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `excluirConta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  excluirConta(context?: HttpContext): Observable<void> {
    return this.excluirConta$Response(context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listarSeguidos()` */
  static readonly ListarSeguidosPath = '/usuarios/{id}/seguindo';

  /**
   * Listar seguidos.
   *
   * Retorna os usuários que um usuário específico segue
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSeguidos()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidos$Response(params: ListarSeguidos$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSeguidos(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar seguidos.
   *
   * Retorna os usuários que um usuário específico segue
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSeguidos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidos(params: ListarSeguidos$Params, context?: HttpContext): Observable<Page> {
    return this.listarSeguidos$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarSeguidores()` */
  static readonly ListarSeguidoresPath = '/usuarios/{id}/seguidores';

  /**
   * Listar seguidores.
   *
   * Retorna os usuários que seguem um usuário específico
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSeguidores()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidores$Response(params: ListarSeguidores$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSeguidores(this.http, this.rootUrl, params, context);
  }

  /**
   * Listar seguidores.
   *
   * Retorna os usuários que seguem um usuário específico
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSeguidores$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSeguidores(params: ListarSeguidores$Params, context?: HttpContext): Observable<Page> {
    return this.listarSeguidores$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `buscarUsuarioPorUsername()` */
  static readonly BuscarUsuarioPorUsernamePath = '/usuarios/username/{username}';

  /**
   * Buscar usuário por username.
   *
   * Retorna os detalhes de um usuário específico pelo username
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarUsuarioPorUsername()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarioPorUsername$Response(params: BuscarUsuarioPorUsername$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return buscarUsuarioPorUsername(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar usuário por username.
   *
   * Retorna os detalhes de um usuário específico pelo username
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarUsuarioPorUsername$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarioPorUsername(params: BuscarUsuarioPorUsername$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.buscarUsuarioPorUsername$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

  /** Path part for operation `listarSugestoesUsuarios()` */
  static readonly ListarSugestoesUsuariosPath = '/usuarios/sugestoes';

  /**
   * Sugestões de usuários.
   *
   * Retorna sugestões de usuários para seguir
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarSugestoesUsuarios()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSugestoesUsuarios$Response(params: ListarSugestoesUsuarios$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarSugestoesUsuarios(this.http, this.rootUrl, params, context);
  }

  /**
   * Sugestões de usuários.
   *
   * Retorna sugestões de usuários para seguir
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarSugestoesUsuarios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarSugestoesUsuarios(params: ListarSugestoesUsuarios$Params, context?: HttpContext): Observable<Page> {
    return this.listarSugestoesUsuarios$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarUsuariosMaisFamosos()` */
  static readonly ListarUsuariosMaisFamososPath = '/usuarios/famosos';

  /**
   * Usuários mais famosos.
   *
   * Retorna uma lista dos usuários mais famosos com base no número de seguidores
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarUsuariosMaisFamosos()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarUsuariosMaisFamosos$Response(params: ListarUsuariosMaisFamosos$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarUsuariosMaisFamosos(this.http, this.rootUrl, params, context);
  }

  /**
   * Usuários mais famosos.
   *
   * Retorna uma lista dos usuários mais famosos com base no número de seguidores
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarUsuariosMaisFamosos$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarUsuariosMaisFamosos(params: ListarUsuariosMaisFamosos$Params, context?: HttpContext): Observable<Page> {
    return this.listarUsuariosMaisFamosos$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `buscarUsuarios()` */
  static readonly BuscarUsuariosPath = '/usuarios/buscar';

  /**
   * Buscar usuários.
   *
   * Retorna usuários que correspondem ao termo de busca
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buscarUsuarios()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarios$Response(params: BuscarUsuarios$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return buscarUsuarios(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar usuários.
   *
   * Retorna usuários que correspondem ao termo de busca
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buscarUsuarios$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buscarUsuarios(params: BuscarUsuarios$Params, context?: HttpContext): Observable<Page> {
    return this.buscarUsuarios$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `listarUsuariosPorAmigosEmComum()` */
  static readonly ListarUsuariosPorAmigosEmComumPath = '/usuarios/amigos-comum';

  /**
   * Buscar usuários por amigos em comum.
   *
   * Retorna uma lista de usuários seguidos por amigos em comum
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listarUsuariosPorAmigosEmComum()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarUsuariosPorAmigosEmComum$Response(params: ListarUsuariosPorAmigosEmComum$Params, context?: HttpContext): Observable<StrictHttpResponse<Page>> {
    return listarUsuariosPorAmigosEmComum(this.http, this.rootUrl, params, context);
  }

  /**
   * Buscar usuários por amigos em comum.
   *
   * Retorna uma lista de usuários seguidos por amigos em comum
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listarUsuariosPorAmigosEmComum$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listarUsuariosPorAmigosEmComum(params: ListarUsuariosPorAmigosEmComum$Params, context?: HttpContext): Observable<Page> {
    return this.listarUsuariosPorAmigosEmComum$Response(params, context).pipe(
      map((r: StrictHttpResponse<Page>): Page => r.body)
    );
  }

  /** Path part for operation `analytics()` */
  static readonly AnalyticsPath = '/usuarios/eu/analytics';

  /**
   * Analytics da conta.
   *
   * Views, alcance e seguidores
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `analytics()` instead.
   *
   * This method doesn't expect any request body.
   */
  analytics$Response(context?: HttpContext): Observable<StrictHttpResponse<AnalyticsDto>> {
    return analytics(this.http, this.rootUrl, context);
  }

  /**
   * Analytics da conta.
   *
   * Views, alcance e seguidores
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `analytics$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  analytics(context?: HttpContext): Observable<AnalyticsDto> {
    return this.analytics$Response(context).pipe(
      map((r: StrictHttpResponse<AnalyticsDto>): AnalyticsDto => r.body)
    );
  }

  /** Path part for operation `atualizarChavePix()` */
  static readonly AtualizarChavePixPath = '/usuarios/eu/pix';

  /**
   * Definir chave Pix.
   *
   * Vazia remove; exibida no perfil
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarChavePix()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarChavePix$Response(params: AtualizarChavePix$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return atualizarChavePix(this.http, this.rootUrl, params, context);
  }

  /**
   * Definir chave Pix.
   *
   * Vazia remove; exibida no perfil
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarChavePix$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  atualizarChavePix(params: AtualizarChavePix$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.atualizarChavePix$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

  /** Path part for operation `atualizarTipoConta()` */
  static readonly AtualizarTipoContaPath = '/usuarios/eu/tipo-conta';

  /**
   * Definir tipo de conta.
   *
   * PESSOAL, CRIADOR ou NEGOCIOS
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `atualizarTipoConta()` instead.
   *
   * This method doesn't expect any request body.
   */
  atualizarTipoConta$Response(params: AtualizarTipoConta$Params, context?: HttpContext): Observable<StrictHttpResponse<UsuarioResponseDto>> {
    return atualizarTipoConta(this.http, this.rootUrl, params, context);
  }

  /**
   * Definir tipo de conta.
   *
   * PESSOAL, CRIADOR ou NEGOCIOS
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `atualizarTipoConta$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  atualizarTipoConta(params: AtualizarTipoConta$Params, context?: HttpContext): Observable<UsuarioResponseDto> {
    return this.atualizarTipoConta$Response(params, context).pipe(
      map((r: StrictHttpResponse<UsuarioResponseDto>): UsuarioResponseDto => r.body)
    );
  }

}
